import {setTrackProperty} from '../../core/layer-commands';
import {toggleMany} from '../../core/selection-commands';
import type {EditorState} from '../../core/editor-state';
import type {Layer,TrackId} from '../../core/project-model';
import type {TimelineNavigationController} from './timeline-navigation-controller';

type MarkerKind='manual'|'beat';
interface TimelineRendererContext {
  state:EditorState;timeline:HTMLElement;head:HTMLElement;rangeStatus:HTMLOutputElement;headerWidth:number;pixelsPerSecond():number;groups():Array<[TrackId,Layer[]]>;trackControls(container:HTMLElement,id:TrackId,clips:Layer[]):void;beginMarquee(event:PointerEvent):void;edit(event:PointerEvent,layer:Layer):void;preview(layer:Layer,element:HTMLElement):void;sourceTimeForLayer(layer:Layer,time:number,mediaDuration?:number):number;showContextMenu(event:MouseEvent,layer?:Layer|null,marker?:{type:MarkerKind;index:number}|null):void;dragMarker(event:PointerEvent,type:MarkerKind,index:number):void;dragRenderBoundary(event:PointerEvent,kind:'start'|'end'):void;navigation:TimelineNavigationController;selectLayer(id:number):void;pushHistory():void;commit():void;renderAudioMixer():void;renderLayersPanel():void;escapeHtml(value:unknown):string;
}
export interface TimelineRenderer {renderTimeline():void;geometry(element:HTMLElement,layer:Layer):void}
const timeText=(time:number):string=>`${Math.floor(time/60).toString().padStart(2,'0')}:${(time%60).toFixed(2).padStart(5,'0')}`;
const rulerText=(time:number):string=>time===0?'0s':time%60===0?`${time/60}m`:String(time%60).padStart(2,'0');
const clipIcon=(type:string):string=>({video:'film',image:'image',audio:'music-2',text:'type',rect:'shapes',circle:'shapes',drawing:'pen-tool',path:'pen-tool',null:'key-round',camera:'maximize'} as Record<string,string>)[type]||'layers';

export function createTimelineRenderer(context:TimelineRendererContext):TimelineRenderer {
  const width=()=>context.state.duration*context.pixelsPerSecond();
  const geometry=(element:HTMLElement,layer:Layer)=>{element.style.left=`${layer.start/context.state.duration*width()}px`;element.style.width=`${Math.max(3,(layer.end-layer.start)/context.state.duration*width())}px`};
  const renderTimeline=()=>{
    context.timeline.querySelectorAll('.track,.timeline-empty,.timeline-marker,.time-ruler,.render-range-overlay').forEach(element=>element.remove());const rulerDuration=Math.max(60,Math.ceil(context.state.duration)+10),contentWidth=rulerDuration*context.pixelsPerSecond(),ruler=document.createElement('div');ruler.className='time-ruler';ruler.style.width=`${context.headerWidth+contentWidth}px`;
    for(let time=0;time<=rulerDuration;time++){const tick=document.createElement('span');tick.style.left=`${context.headerWidth+time*context.pixelsPerSecond()}px`;tick.dataset.second=String(time);tick.className=time%5===0?'major-tick':'minor-tick';if(time%5===0)tick.textContent=rulerText(time);ruler.append(tick)}
    const corner=document.createElement('div');corner.className='ruler-corner';corner.innerHTML='<i></i><span>Camadas</span>';corner.onpointerdown=event=>event.stopPropagation();ruler.append(corner);context.navigation.setActiveCorner(corner);ruler.onpointerdown=context.navigation.scrub;context.timeline.insertBefore(ruler,context.head);
    for(const [id,clips] of context.groups()){
      const row=document.createElement('div');row.className='track';row.dataset.track=String(id);row.style.width=`${context.headerWidth+contentWidth}px`;row.style.gridTemplateColumns=`${context.headerWidth}px ${contentWidth}px`;row.dataset.kind=clips.some(layer=>['video','image'].includes(layer.type))?'video':clips.every(layer=>layer.type==='audio')?'audio':'text';const name=document.createElement('div');name.className='track-name';const representative=clips.find(layer=>layer.id===context.state.selection.selected)||clips[0],audioClips=clips.filter(layer=>layer.type==='audio'||layer.type==='video'),hasAudio=clips.some(layer=>layer.type==='audio'||layer.type==='video'&&layer.hasAudio),last=clips.at(-1)!;
      name.innerHTML=`<span class="layer-title">${context.escapeHtml(last.name)}</span><button data-lock title="Bloquear faixa">${clips.every(layer=>layer.locked)?'🔒':'🔓'}</button><button data-vis title="Ocultar faixa">${clips.some(layer=>layer.visible!==false)?'●':'○'}</button><button data-mute title="Silenciar faixa" ${hasAudio?'':'disabled'}>${hasAudio&&audioClips.every(layer=>layer.muted)?'🔇':'🔊'}</button><button data-multi title="Marcar clipes para precomposição">☐</button>`;
      const ids=clips.flatMap(layer=>layer.id===undefined?[]:[layer.id]),visible=name.querySelector<HTMLButtonElement>('[data-vis]')!,lock=name.querySelector<HTMLButtonElement>('[data-lock]')!,mute=name.querySelector<HTMLButtonElement>('[data-mute]')!,multi=name.querySelector<HTMLButtonElement>('[data-multi]')!;
      visible.onclick=event=>{event.stopPropagation();context.pushHistory();setTrackProperty(context.state,{ids,key:'visible',value:!clips.some(layer=>layer.visible!==false)});context.commit()};lock.onclick=event=>{event.stopPropagation();context.pushHistory();setTrackProperty(context.state,{ids,key:'locked',value:!clips.every(layer=>layer.locked)});context.commit()};mute.onclick=event=>{event.stopPropagation();if(!hasAudio)return;context.pushHistory();setTrackProperty(context.state,{ids:audioClips.flatMap(layer=>layer.id===undefined?[]:[layer.id]),key:'muted',value:!audioClips.every(layer=>layer.muted)});context.commit()};multi.onclick=event=>{event.stopPropagation();toggleMany(context.state,ids);renderTimeline()};multi.textContent=ids.every(idValue=>context.state.selection.selectedIds.has(idValue))?'☑':'☐';const title=name.querySelector<HTMLElement>('span');if(title&&representative.id!==undefined)title.onclick=()=>context.selectLayer(representative.id!);context.trackControls(name,id,clips);
      const lane=document.createElement('div');lane.className='track-lane';lane.onpointerdown=event=>{if(event.target===lane)context.beginMarquee(event)};
      for(const layer of clips){if(layer.id===undefined)continue;const clip=document.createElement('div');clip.className='clip pro-clip'+(context.state.selection.selected===layer.id||context.state.selection.selectedIds.has(layer.id)?' selected-clip':'');clip.dataset.clip=String(layer.id);geometry(clip,layer);clip.style.opacity=layer.visible===false?'.35':'1';clip.dataset.kind=layer.type;clip.title=`${layer.name} · ${timeText(layer.end-layer.start)}`;clip.style.setProperty('--clip-icon',`url("assets/icons/${clipIcon(layer.type)}.svg")`);clip.innerHTML=`<div class="filmstrip"></div><span class="clip-label"><i class="clip-kind-icon"></i><span class="clip-title">${context.escapeHtml(layer.name)}</span></span><i class="clip-handle left"></i><i class="clip-handle right"></i>`;
        for(const keyframe of layer.keyframes){if(keyframe.time<layer.start||keyframe.time>layer.end)continue;const dot=document.createElement('i');dot.className='key-dot';dot.style.left=`${(keyframe.time-layer.start)/(layer.end-layer.start)*100}%`;clip.append(dot)}
        if(layer.type==='audio'&&layer.waveform?.length){const wave=document.createElement('canvas');wave.className='clip-waveform';wave.width=Math.min(4096,Math.max(40,(layer.end-layer.start)*context.pixelsPerSecond()));wave.height=24;const drawing=wave.getContext('2d');if(drawing){drawing.fillStyle='#073c2d';for(let x=0;x<wave.width;x+=4){const source=context.sourceTimeForLayer(layer,layer.start+x/wave.width*(layer.end-layer.start),layer.mediaDuration),index=Math.min(layer.waveform.length-1,Math.floor(source/(layer.mediaDuration||context.state.duration)*layer.waveform.length)),value=layer.waveform[index]||0;drawing.fillRect(x,12-value*10,2,Math.max(2,value*20))}}clip.append(wave)}
        clip.onpointerdown=event=>context.edit(event,layer);clip.oncontextmenu=event=>context.showContextMenu(event,layer);lane.append(clip);const filmstrip=clip.querySelector<HTMLElement>('.filmstrip');if(filmstrip)context.preview(layer,filmstrip);
      }
      row.append(name,lane);context.timeline.insertBefore(row,context.head);
    }
    const drawMarkers=(items:number[],type:MarkerKind)=>items.forEach((time,index)=>{const marker=document.createElement('i');marker.className=`timeline-marker ${type==='beat'?'beat-marker':'manual-marker'}`;marker.dataset.markerType=type;marker.dataset.markerIndex=String(index);marker.style.left=`${context.headerWidth+time*context.pixelsPerSecond()}px`;marker.title=`${type==='beat'?'Beat sync':'Marcador manual'} · ${timeText(time)} · arraste ou botão direito`;marker.onpointerdown=event=>context.dragMarker(event,type,index);marker.oncontextmenu=event=>context.showContextMenu(event,null,{type,index});ruler.append(marker)});drawMarkers(context.state.markers,'manual');drawMarkers(context.state.beatMarkers,'beat');
    const range=context.state.renderRange||{start:0,end:context.state.duration};for(const kind of ['start','end'] as const){const marker=document.createElement('i');marker.className=`timeline-range-marker range-${kind}`;marker.dataset.rangeBoundary=kind;marker.style.left=`${context.headerWidth+range[kind]*context.pixelsPerSecond()}px`;marker.title=`${kind==='start'?'Início':'Fim'} da renderização · ${timeText(range[kind])} · arraste para mover`;marker.onpointerdown=event=>context.dragRenderBoundary(event,kind);ruler.append(marker)}context.rangeStatus.value=`Render ${timeText(range.start)}–${timeText(range.end)}`;context.rangeStatus.textContent=context.rangeStatus.value;context.head.style.bottom='auto';context.head.style.height=`${Math.max(context.timeline.clientHeight,ruler.offsetHeight+[...context.timeline.querySelectorAll<HTMLElement>('.track')].reduce((sum,row)=>sum+row.offsetHeight,0))}px`;context.navigation.positionCorner();context.renderAudioMixer();context.renderLayersPanel();context.navigation.position();
  };
  return{renderTimeline,geometry};
}
