import {generateBeats,setMarkers} from '../../core/project-commands';
import type {EditorState} from '../../core/editor-state';
import type {Layer} from '../../core/project-model';

interface TimelineBeatContext {state:EditorState;button:HTMLButtonElement;selected():Layer|null;pushHistory():void;renderTimeline():void;markDirty():void;toast(message:string):void}

const clamp=(value:number,min:number,max:number):number=>Math.max(min,Math.min(max,value));

export function installTimelineBeatController(context:TimelineBeatContext):void {
  const panel=document.createElement('div');panel.className='floating-dropdown beat-sync-panel';panel.hidden=true;panel.innerHTML='<strong>Beat sync</strong><label>BPM <input data-beat-bpm type="number" min="30" max="300" step="0.01" value="120"></label><label>Início (s) <input data-beat-offset type="number" min="0" step="0.001" value="0"></label><button data-beat-analyze>Estimar pela waveform</button><button data-beat-generate>Gerar grade</button><button data-beat-clear>Remover beat sync</button><small>A grade mantém o tempo constante. A estimativa usa os picos apenas para sugerir BPM e fase.</small>';document.body.append(panel);
  const bpm=panel.querySelector<HTMLInputElement>('[data-beat-bpm]'),offset=panel.querySelector<HTMLInputElement>('[data-beat-offset]');if(!bpm||!offset)throw new Error('Controles de beat sync ausentes');bpm.value=String(context.state.beatSync.bpm||120);offset.value=String(context.state.beatSync.offset||0);
  context.button.onclick=event=>{event.stopPropagation();panel.hidden=!panel.hidden;if(!panel.hidden){const bounds=context.button.getBoundingClientRect();panel.style.left=`${Math.min(innerWidth-panel.offsetWidth-12,bounds.left)}px`;panel.style.top=`${bounds.bottom+6}px`}};
  document.addEventListener('pointerdown',event=>{if(!panel.hidden&&!panel.contains(event.target as Node)&&event.target!==context.button)panel.hidden=true});
  const estimate=()=>{const layer=context.selected(),waveform=layer?.waveform;if(!layer||!['audio','video'].includes(layer.type)||!waveform?.length)return context.toast('Selecione um clipe com waveform');const duration=layer.mediaDuration||(layer.end-layer.start)*layer.speed,secondsPerPoint=duration/waveform.length;let best={score:-Infinity,bpm:120,lag:1};for(let candidate=60;candidate<=200;candidate+=.25){const lag=60/candidate/secondsPerPoint;if(lag<1||lag>=waveform.length/2)continue;let score=0,count=0;for(let index=0;index+lag<waveform.length;index++){const next=Math.round(index+lag);score+=(waveform[index]||0)*(waveform[next]||0);count++}score/=Math.max(1,count);if(score>best.score)best={score,bpm:candidate,lag}}const interval=60/best.bpm;let peak=0;for(let index=1;index<waveform.length;index++)if(waveform[index]>waveform[peak])peak=index;const peakTimeline=layer.start+(peak*secondsPerPoint-layer.sourceIn)/layer.speed,suggestedOffset=((peakTimeline%interval)+interval)%interval;bpm.value=best.bpm.toFixed(2);offset.value=Math.max(0,suggestedOffset).toFixed(3);context.toast(`Sugestão: ${best.bpm.toFixed(2)} BPM`)};
  const generate=()=>{const value=clamp(Number(bpm.value)||120,30,300),start=clamp(Number(offset.value)||0,0,context.state.duration);generateBeats(context.state,{bpm:value,offset:start});context.pushHistory();context.renderTimeline();context.markDirty();context.toast(`${context.state.beatMarkers.length} marcadores de beat sync gerados`)};
  panel.querySelector<HTMLButtonElement>('[data-beat-analyze]')!.onclick=estimate;panel.querySelector<HTMLButtonElement>('[data-beat-generate]')!.onclick=generate;panel.querySelector<HTMLButtonElement>('[data-beat-clear]')!.onclick=()=>{setMarkers(context.state,{kind:'beat',markers:[]});context.pushHistory();context.renderTimeline();context.markDirty();context.toast('Marcadores do beat sync removidos')};
}
