import {canPlaceClipOnTrack,duplicate,freezeFrame,moveClipToTrack,removeMany,split,trackIdFor} from '../../core/layer-commands';
import {setProperties} from '../../core/project-commands';
import type {EditorState} from '../../core/editor-state';
import type {Layer,TrackId} from '../../core/project-model';

interface TimelineActionsContext {
  state:EditorState;tools:HTMLElement;groups():Array<[TrackId,Layer[]]>;nextId():number;selected():Layer|null;captureFrame(layer:Layer,time:number):Promise<{content:string;mediaDuration:number}>;detachAudio(layer?:Layer):void;stop():void;pushHistory():void;syncComposition():void;commit():void;selectLayer(id:number):void;renderMediaLibrary():void;toast(message:string):void;
}

const byId=<T extends HTMLElement>(id:string):T=>{const element=document.getElementById(id);if(!element)throw new Error(`Elemento ausente: ${id}`);return element as T};

export function installTimelineActionsController(context:TimelineActionsContext):void {
  const duplicateButton=byId<HTMLButtonElement>('duplicateLayer');duplicateButton.onclick=()=>{const selectedId=context.state.selection.selected;if(selectedId===null)return;context.pushHistory();const copy=duplicate(context.state,selectedId,context.nextId());if(copy?.id!==undefined){context.commit();context.selectLayer(copy.id)}};
  const newProject=byId<HTMLButtonElement>('newProject'),resetProject=newProject.onclick;newProject.onclick=event=>{resetProject?.call(newProject,event);context.renderMediaLibrary()};
  const deleteButton=byId<HTMLButtonElement>('deleteLayer');deleteButton.onclick=()=>{const selected=context.state.selection.selected,selectedIds=context.state.selection.selectedIds.size?[...context.state.selection.selectedIds]:selected===null?[]:[selected];if(!selectedIds.length)return;context.pushHistory();const removed=removeMany(context.state,selectedIds);if(removed.length){context.commit();context.toast(`${removed.length} clipes excluídos`)}};
  const freeze=async(layer:Layer)=>{if(layer.type!=='video'||layer.id===undefined)return context.toast('Selecione um clipe de vídeo');const time=context.state.playback.time;if(time<layer.start||time>=layer.end)return context.toast('Posicione o cursor dentro do clipe');const original=JSON.stringify(layer),button=context.tools.querySelector<HTMLButtonElement>('[data-action="freeze"]');context.stop();if(button)button.disabled=true;
    try{const {content,mediaDuration}=await context.captureFrame(layer,time);if(!context.state.layers.includes(layer)||JSON.stringify(layer)!==original)return context.toast('O clipe mudou durante a captura. Tente novamente.');context.pushHistory();const still=freezeFrame(context.state,{id:layer.id,time,content,stillId:context.nextId(),rightId:context.nextId(),hold:2,mediaDuration});if(!still?.id)return context.toast('O clipe mudou durante a captura. Tente novamente.');context.syncComposition();context.commit();context.selectLayer(still.id);context.toast('Quadro congelado por 2 segundos; ajuste pelas bordas')}catch{context.toast('Não foi possível capturar o quadro deste vídeo')}finally{if(button)button.disabled=false}
  };
  const moveTrack=(direction:-1|1)=>{const layer=context.selected();if(!layer?.id||layer.locked)return;const currentTrack=trackIdFor(layer);if(currentTrack===null)return;const rows=context.groups(),index=rows.findIndex(([id])=>id===currentTrack),target=rows[index+direction];if(target&&!canPlaceClipOnTrack(context.state,{id:layer.id,trackId:target[0],start:layer.start,end:layer.end}))return context.toast('A faixa de destino está bloqueada ou já tem um clipe nesse intervalo');const placement=target?{destinationTrackId:target[0]}:{newTrack:{id:`track-${crypto.randomUUID()}`,name:layer.name,targetTrackId:rows[index][0],before:direction<0}};context.pushHistory();if(moveClipToTrack(context.state,{id:layer.id,placement}))context.commit()};
  const splitSelected=()=>{const layer=context.selected();if(!layer?.id||layer.locked)return;if(context.state.playback.time<=layer.start||context.state.playback.time>=layer.end)return context.toast('Posicione o cursor dentro do clipe');context.pushHistory();trackIdFor(layer);const right=split(context.state,layer.id,context.state.playback.time,context.nextId());if(right?.id!==undefined){context.commit();context.selectLayer(right.id)}};byId<HTMLButtonElement>('splitAtPlayhead').onclick=splitSelected;
  context.tools.addEventListener('click',async event=>{const action=(event.target as HTMLElement).dataset.action;if(!['freeze','reverse','flip'].includes(action||''))return;const layer=context.selected();if(!layer?.id)return context.toast('Selecione um clipe');if(layer.locked)return context.toast('Faixa bloqueada');if(action==='freeze'){await freeze(layer);return}if(action==='reverse'&&layer.type!=='video')return context.toast('Selecione um clipe de vídeo');if(action==='flip'&&['audio','null','camera'].includes(layer.type))return context.toast('Selecione um clipe visual');context.stop();context.pushHistory();const key=action==='reverse'?'reverse':'flipX';setProperties(context.state,{id:layer.id,values:{[key]:!layer[key]}});context.commit();context.selectLayer(layer.id)});
  context.tools.onclick=event=>{const action=(event.target as HTMLElement).dataset.action;if(action==='play')byId<HTMLButtonElement>('playBtn').click();if(action==='split')splitSelected();if(action==='delete')deleteButton.click();if(action==='extract-audio')context.detachAudio();if(action==='up'||action==='down')moveTrack(action==='up'?-1:1)};
}
