/* Ferramentas de edição: keyframes, desenho, composição e projetos. */
const featureMap={
  'Projeto e arquivos':['Criar, renomear e salvar projetos','Importar/exportar projeto JSON','Importar/exportar cenas XML compatíveis com Alight Motion','Composições 16:9, 9:16, 1:1 e 4:5','Resolução, FPS, duração e fundo','Templates, presets e pacotes de elementos'],
  'Camadas':['Vídeo, imagem, áudio, texto e formas','Desenho vetorial livre','Duplicar, excluir e reordenar','Agrupamento e pré-composição','Entrada, saída e recorte temporal','Máscaras, clipping e parenting'],
  'Animação':['Keyframes por propriedade','Easing linear, suave, aceleração, desaceleração e rebote','Posição, escala, rotação e opacidade','Caminhos de movimento e gráfico de curva','Parenting, nulos e precomposição','Retiming, reverso e velocidade de mídia'],
  'Visual':['Cor sólida e gradientes','Contorno, cantos, transparência e máscaras','Modos de mesclagem','Glow, vinheta, blur, nitidez, contraste e matiz','Chroma key, canais RGB, saturação, sépia e inversão','Recorte, âncora e espelhamento'],
  'Texto e vetores':['Família e tamanho de fonte','Alinhamento e cor','Formas retângulo/círculo','Splines e desenho manual','Preenchimento e contorno','Elementos nulos e grupos'],
  'Mídia e saída':['Navegador de mídia, waveform e mixer','Preview sincronizado','Canais L/R, pan, solo, mute e fades','MP4, MOV, WebM, GIF, PNG e MP3','Presets 720p, 1080p, 1440p e 4K','Qualidade, FPS, bitrate, faixa e transparência'],
  'Experiência offline':['Sem anúncios','Sem pagamentos ou assinatura','Sem conta obrigatória','Projetos armazenados localmente','Sem notificações promocionais','Sem telemetria']
};

state.composition={width:1920,height:1080,fps:30,background:'#08090b'};
const projectHistory=MotionHistory.createHistory({limit:40});state.drawing=false;
const originalAddLayer=addLayer,originalApplyStyle=applyStyle,originalSetTime=setTime;
addLayer=function(type,content,name){const l=MotionProject.applyLayerDefaults(originalAddLayer(type,content,name),state.duration);queueMicrotask(pushHistory);return l};
applyStyle=function(e,l){originalApplyStyle(e,l);e.style.mixBlendMode=l.blend||'normal';e.style.borderRadius=(l.radius||0)+'%';e.style.webkitTextStroke=`${l.stroke||0}px ${l.strokeColor||'#000'}`;e.style.fontFamily=l.font||'Segoe UI';e.style.fontSize=(l.fontSize||42)+'px';e.classList.toggle('mask',!!l.mask);e.hidden=state.time<(l.start||0)||state.time>=(l.end??state.duration)};
function snapshot(){return JSON.stringify(projectData())}
function pushHistory(){projectHistory.push(snapshot())}
function restore(raw){stop();MotionProjectSession.apply(state,JSON.parse(raw));$('#projectName').value=state.name;$('#aspect').value=state.aspect;restoreMediaLibrary(state);syncComposition();renderLayers();syncProps();setTime(state.time);markDirty()}
$('#undoBtn').onclick=()=>{pushHistory();const value=projectHistory.undo();if(value===null)return;restore(value);toast('Desfeito')};
$('#redoBtn').onclick=()=>{const value=projectHistory.redo();if(value===null)return;restore(value);toast('Refeito')};

function syncComposition(){const c=state.composition;$('#compWidth').value=c.width;$('#compHeight').value=c.height;$('#compFps').value=c.fps;$('#compDuration').value=state.duration;$('#compBackground').value=c.background;$('#stage').style.background=c.background;$('#timeSlider').max=state.duration}
$('#applyComposition').onclick=()=>{try{MotionProjectCommands.setComposition(state,{width:+$('#compWidth').value,height:+$('#compHeight').value,fps:+$('#compFps').value,duration:+$('#compDuration').value,background:$('#compBackground').value});syncComposition();renderLayers();setTime(state.time);pushHistory();markDirty();toast('Composição atualizada')}catch(error){toast(error.message)}};

function interpolate(l,time){return MotionAnimation.evaluateLayer(l,time,{layers:state.layers,duration:state.duration})}
setTime=function(t){originalSetTime(t);for(const l of state.layers){const e=$('.layer[data-id="'+l.id+'"]');if(e)applyStyle(e,interpolate(l,state.time))}};

const advancedFields={Start:'start',End:'end',AnchorX:'anchorX',AnchorY:'anchorY',CropX:'cropX',CropY:'cropY',FitMode:'fitMode',Visible:'visible',Locked:'locked',FlipX:'flipX',FlipY:'flipY',Blend:'blend',Radius:'radius',Stroke:'stroke',StrokeColor:'strokeColor',Font:'font',FontSize:'fontSize',Mask:'mask'};
for(const [id,key] of Object.entries(advancedFields)){const el=$('#prop'+id);el.oninput=e=>{const l=selected();if(!l)return;l[key]=el.type==='checkbox'?el.checked:(el.type==='range'||el.type==='number'?+el.value:el.value);updateSelected();syncAdvancedProps();markDirty()}}
function syncAdvancedProps(){const l=selected();if(!l)return;for(const [id,key] of Object.entries(advancedFields)){const el=$('#prop'+id);if(el.type==='checkbox')el.checked=key==='visible'?l[key]!==false:!!l[key];else el.value=l[key]??({end:state.duration,fontSize:42,anchorX:50,anchorY:50,fitMode:'contain'}[key]??0);const out=$('#out'+id);if(out)out.value=el.value+(key==='radius'||key==='fontSize'?'px':'') }}
const oldSyncProps=syncProps;syncProps=function(){oldSyncProps();syncAdvancedProps()};

function requireVideo(){const l=selected();if(!l||!['video','audio'].includes(l.type)){toast('Selecione uma camada de vídeo ou áudio');return null}return l}
for(const [id,edge] of [['setInPoint','start'],['setOutPoint','end']])$('#'+id).onclick=()=>{const l=requireVideo();if(!l)return;if(!MotionProjectCommands.trim(state,{id:l.id,edge,time:state.time}))return toast('Posicione o cursor dentro de um clipe desbloqueado');renderLayers();selectLayer(l.id);pushHistory();markDirty();toast(edge==='start'?'Entrada definida':'Saída definida')};
$('#resetTrim').onclick=()=>{const l=requireVideo();if(!l||!MotionProjectCommands.resetTrim(state,{id:l.id}))return;renderLayers();selectLayer(l.id);pushHistory();markDirty();toast('Corte restaurado')};
for(const [id,key] of [['propSpeed','speed'],['propVolume','volume'],['propFadeIn','fadeIn'],['propFadeOut','fadeOut'],['propMuted','muted']])$('#'+id).oninput=e=>{const l=requireVideo();if(!l)return;l[key]=e.target.type==='checkbox'?e.target.checked:+e.target.value;if(key==='speed')$('#outSpeed').value=l.speed.toFixed(2)+'×';if(key==='volume')$('#outVolume').value=l.volume+'%';const v=$(`.layer[data-id="${l.id}"] video`);if(v){v.muted=l.muted;v.volume=Math.min(1,l.volume/100);v.playbackRate=l.speed}markDirty()};

const effectKeys={Brightness:'brightness',Contrast:'contrast',Saturation:'saturation',Hue:'hue',Blur:'blur',Grayscale:'grayscale',Sepia:'sepia',Invert:'invert'};
function buildFilter(l){const f=l.effects||{};return `brightness(${(f.brightness??100)/100}) contrast(${(f.contrast??100)/100}) saturate(${(f.saturation??100)/100}) hue-rotate(${f.hue||0}deg) blur(${f.blur||0}px) grayscale(${(f.grayscale||0)/100}) sepia(${(f.sepia||0)/100}) invert(${(f.invert||0)/100})`}
for(const [id,key] of Object.entries(effectKeys))$('#fx'+id).oninput=e=>{const l=selected();if(!l)return toast('Selecione uma camada');l.effects=l.effects||{};l.effects[key]=+e.target.value;l.filter=buildFilter(l);$('#out'+id).value=e.target.value+(key==='hue'?'°':key==='blur'?'px':'%');updateSelected();markDirty()};
$('#resetEffects').onclick=()=>{const l=selected();if(!l)return;l.effects={brightness:100,contrast:100,saturation:100,hue:0,blur:0,grayscale:0,sepia:0,invert:0};l.filter=buildFilter(l);syncAdvancedProps();updateSelected();markDirty();toast('Efeitos restaurados')};
$$('[data-effect]').forEach(b=>b.onclick=()=>{const l=selected();if(!l)return toast('Selecione uma camada');const presets={'none':{},'grayscale(1)':{grayscale:100},'sepia(.8)':{sepia:80},'blur(3px)':{blur:3},'contrast(1.5)':{contrast:150},'saturate(1.8)':{saturation:180},'brightness(1.35)':{brightness:135},'hue-rotate(90deg)':{hue:90},'invert(1)':{invert:100},'drop-shadow(8px 8px 8px #000)':{contrast:115,brightness:85}};l.effects={brightness:100,contrast:100,saturation:100,hue:0,blur:0,grayscale:0,sepia:0,invert:0,...presets[b.dataset.effect]};l.filter=buildFilter(l);syncAdvancedProps();updateSelected();markDirty();toast('Efeito aplicado')});

const previousSyncAdvancedProps=syncAdvancedProps;syncAdvancedProps=function(){previousSyncAdvancedProps();const l=selected();if(!l)return;$('#propSpeed').value=l.speed||1;$('#outSpeed').value=(l.speed||1).toFixed(2)+'×';$('#propVolume').value=l.volume??100;$('#outVolume').value=(l.volume??100)+'%';$('#propFadeIn').value=l.fadeIn||0;$('#propFadeOut').value=l.fadeOut||0;$('#propMuted').checked=!!l.muted;for(const [id,key] of Object.entries(effectKeys)){const value=l.effects?.[key]??(key==='brightness'||key==='contrast'||key==='saturation'?100:0);$('#fx'+id).value=value;$('#out'+id).value=value+(key==='hue'?'°':key==='blur'?'px':'%')}};

function moveSelected(delta){if(!MotionLayerCommands.move(state,state.selected,delta))return;renderLayers();selectLayer(state.selected);pushHistory()}
$('#moveLayerUp').onclick=()=>moveSelected(1);$('#moveLayerDown').onclick=()=>moveSelected(-1);
$('#groupLayer').onclick=()=>{const l=selected();if(!l)return;l.group=l.group?null:`Grupo ${Date.now().toString().slice(-4)}`;l.name=l.group?`${l.group} · ${l.name}`:l.name.replace(/^Grupo \d+ · /,'');renderTimeline();pushHistory();toast(l.group?'Camada agrupada':'Grupo removido')};


function renderAudioMixer(){const box=$('#audioMixer');if(!box)return;const channels=state.layers.filter(l=>l.type==='audio'||l.type==='video');if(!channels.length){box.innerHTML='<div class="empty">Importe áudio ou um vídeo com som</div>';return}box.innerHTML='';for(const l of channels){const card=document.createElement('div');card.className='audio-channel',rawVolume=Number(l.volume),rawPan=Number(l.pan),volume=Math.max(0,Math.min(200,Number.isFinite(rawVolume)?rawVolume:100)),pan=Math.max(-100,Math.min(100,Number.isFinite(rawPan)?rawPan:0));card.innerHTML=`<strong>${l.type==='video'?'🎬':'♫'} ${escapeHtml(l.name)}</strong><label>Volume ${volume}%<input data-volume type="range" min="0" max="200" value="${volume}"></label><label>Pan L/R ${pan}<input data-pan type="range" min="-100" max="100" value="${pan}"></label><label>Fonte<select data-channel><option value="stereo">Estéreo</option><option value="left">Somente canal esquerdo</option><option value="right">Somente canal direito</option></select></label><label><input data-mute type="checkbox" ${l.muted?'checked':''}> Mudo</label><label><input data-solo type="checkbox" ${l.solo?'checked':''}> Solo</label>`;card.onclick=()=>selectLayer(l.id);card.querySelector('[data-channel]').value=['stereo','left','right'].includes(l.audioChannel)?l.audioChannel:'stereo';card.querySelector('[data-volume]').oninput=e=>{l.volume=+e.target.value;renderAudioMixer();markDirty()};card.querySelector('[data-pan]').oninput=e=>{l.pan=+e.target.value;renderAudioMixer();markDirty()};card.querySelector('[data-channel]').onchange=e=>{l.audioChannel=e.target.value;markDirty()};card.querySelector('[data-mute]').onchange=e=>{l.muted=e.target.checked;renderLayers();markDirty()};card.querySelector('[data-solo]').onchange=e=>{l.solo=e.target.checked;renderAudioMixer();markDirty()};box.append(card)}}

$('#startDrawing').onclick=()=>{state.drawing=!state.drawing;$('#stage').classList.toggle('drawing',state.drawing);$('#startDrawing').textContent=state.drawing?'Desenho ativo — arraste no palco':'Iniciar desenho';toast(state.drawing?'Modo desenho ativo':'Modo desenho encerrado')};
let drawPoints=[];
$('#stage').addEventListener('pointerdown',e=>{if(!state.drawing||e.target!==$('#stage'))return;e.preventDefault();drawPoints=[];const r=$('#stage').getBoundingClientRect();const point=x=>drawPoints.push([(x.clientX-r.left)/r.width*640,(x.clientY-r.top)/r.height*360]);point(e);const move=x=>point(x);const up=()=>{removeEventListener('pointermove',move);removeEventListener('pointerup',up);if(drawPoints.length<2)return;const c=document.createElement('canvas');c.width=640;c.height=360;const g=c.getContext('2d');g.strokeStyle=$('#brushColor').value;g.lineWidth=+$('#brushSize').value;g.lineCap='round';g.lineJoin='round';g.beginPath();drawPoints.forEach((p,i)=>i?g.lineTo(...p):g.moveTo(...p));g.stroke();addLayer('drawing',c.toDataURL(),'Desenho livre');state.drawing=false;$('#stage').classList.remove('drawing');$('#startDrawing').textContent='Iniciar desenho'};addEventListener('pointermove',move);addEventListener('pointerup',up)});
$('#clearDrawing').onclick=()=>{const l=selected();if(l?.type==='drawing'){$('#deleteLayer').click()}else toast('Selecione uma camada de desenho')};


function projectData(){return MotionProjectSession.encode(state,{name:$('#projectName').value,aspect:$('#aspect').value})}
function downloadJson(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(projectData(),null,2)],{type:'application/json'}));a.download=($('#projectName').value||'projeto')+'.motion.json';a.click();toast('Projeto JSON exportado')}
$('#exportProject').onclick=downloadJson;$('#menuExport').onclick=downloadJson;
$('#importProject').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>50*1024*1024)throw new Error('Projeto acima de 50 MB');loadProjectData(JSON.parse(await f.text()));toast('Projeto importado')}catch{toast('Arquivo de projeto inválido')}finally{e.target.value=''}};
$('#menuImport').onclick=()=>$('#importProject').click();
$('#projectFile').onclick=()=>$('#projectMenu').hidden=!$('#projectMenu').hidden;
$('#menuFeatures').onclick=()=>{$('#featureModal').hidden=false;$('#projectMenu').hidden=true};$('#closeFeatures').onclick=()=>$('#featureModal').hidden=true;
$('#featureGrid').className='feature-grid';$('#featureGrid').innerHTML=Object.entries(featureMap).map(([title,items])=>`<section class="feature-card"><h3>${title}</h3><ul>${items.map(x=>`<li>${x}</li>`).join('')}</ul></section>`).join('');

document.addEventListener('keydown',e=>{const editing=!!e.target.closest?.('input,textarea,select,[contenteditable="true"]');if(!editing&&e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();$('#undoBtn').click()}if(!editing&&e.ctrlKey&&e.key.toLowerCase()==='y'){e.preventDefault();$('#redoBtn').click()}if(!editing&&e.key==='Delete'&&state.selected)$('#deleteLayer').click();if(!editing&&e.code==='Space'){e.preventDefault();$('#playBtn').click()}});
syncComposition();pushHistory();renderLayers();
