/* Ferramentas de edição: keyframes, desenho, composição e projetos. */
const featureMap={
  'Projeto e arquivos':['Criar, renomear e salvar projetos','Importar/exportar projeto JSON','Importar/exportar cenas XML compatíveis com Alight Motion','Composições 16:9, 9:16, 1:1 e 4:5','Resolução, FPS, duração e fundo','Templates, presets e pacotes de elementos'],
  'Camadas':['Vídeo, imagem, áudio, texto e formas','Desenho vetorial livre','Duplicar, excluir e reordenar','Agrupamento e pré-composição','Entrada, saída e recorte temporal','Máscaras, clipping e parenting'],
  'Animação':['Keyframes por propriedade','Easing linear, suave, aceleração, desaceleração e rebote','Posição, escala, rotação e opacidade','Caminhos de movimento e gráfico de curva','Parenting, nulos e precomposição','Retiming, reverso e velocidade de mídia'],
  'Visual':['Cor sólida e gradientes','Contorno, cantos, transparência e máscaras','Modos de mesclagem','Glow, vinheta, blur, nitidez, contraste e matiz','Chroma key, canais RGB, saturação, sépia e inversão','Recorte, âncora e espelhamento'],
  'Texto e vetores':['Família e tamanho de fonte','Alinhamento e cor','Formas retângulo/círculo','Splines e desenho manual','Preenchimento e contorno','Elementos nulos e grupos'],
  'Mídia e saída':['Navegador de mídia, waveform e mixer','Preview sincronizado','Canais L/R, pan, solo, mute e fades','MP4, MOV, WebM, GIF, PNG e MP3','Presets 720p, 1080p, 1440p e 4K','Qualidade, FPS, bitrate, faixa e transparência'],
  'Experiência offline':['Sem anúncios','Sem pagamentos ou assinatura','Sem conta obrigatória','Projetos armazenados localmente','Sem notificações promocionais','Sem telemetria']
};

state.composition={width:1920,height:1080,fps:30,background:'#08090b'};
state.history=[];state.future=[];state.drawing=false;
const originalAddLayer=addLayer,originalApplyStyle=applyStyle,originalSetTime=setTime;
addLayer=function(type,content,name){const l=originalAddLayer(type,content,name);Object.assign(l,{start:0,end:state.duration,sourceIn:0,sourceOut:state.duration,mediaDuration:0,speed:1,volume:100,pan:0,audioChannel:'stereo',muted:false,solo:false,fadeIn:0,fadeOut:0,visible:true,locked:false,anchorX:50,anchorY:50,cropX:0,cropY:0,flipX:false,flipY:false,blend:'normal',radius:0,stroke:0,strokeColor:'#000000',font:'Segoe UI',fontSize:42,mask:false,keyframes:[],group:null,effects:{brightness:100,contrast:100,saturation:100,hue:0,blur:0,grayscale:0,sepia:0,invert:0}});pushHistory();return l};
applyStyle=function(e,l){originalApplyStyle(e,l);e.style.mixBlendMode=l.blend||'normal';e.style.borderRadius=(l.radius||0)+'%';e.style.webkitTextStroke=`${l.stroke||0}px ${l.strokeColor||'#000'}`;e.style.fontFamily=l.font||'Segoe UI';e.style.fontSize=(l.fontSize||42)+'px';e.classList.toggle('mask',!!l.mask);e.hidden=state.time<(l.start||0)||state.time>(l.end??state.duration)};
function snapshot(){return JSON.stringify({layers:state.layers.map(l=>({...l,content:['image','video','audio','drawing'].includes(l.type)?'':l.content})),composition:state.composition,duration:state.duration,markers:state.markers||[]})}
function pushHistory(){const s=snapshot();if(state.history.at(-1)!==s){state.history.push(s);if(state.history.length>40)state.history.shift()}state.future=[]}
function restore(raw){const d=JSON.parse(raw);state.layers=d.layers||[];state.composition=d.composition||state.composition;state.duration=d.duration||10;state.markers=d.markers||[];state.selected=null;syncComposition();renderLayers();syncProps();setTime(Math.min(state.time,state.duration))}
$('#undoBtn').onclick=()=>{if(state.history.length<2)return;state.future.push(state.history.pop());restore(state.history.at(-1));toast('Desfeito')};
$('#redoBtn').onclick=()=>{if(!state.future.length)return;const s=state.future.pop();state.history.push(s);restore(s);toast('Refeito')};

function syncComposition(){const c=state.composition;$('#compWidth').value=c.width;$('#compHeight').value=c.height;$('#compFps').value=c.fps;$('#compDuration').value=state.duration;$('#compBackground').value=c.background;$('#stage').style.background=c.background;$('#timeSlider').max=state.duration}
$('#applyComposition').onclick=()=>{state.composition={width:+$('#compWidth').value,height:+$('#compHeight').value,fps:+$('#compFps').value,background:$('#compBackground').value};state.duration=+$('#compDuration').value;state.layers.forEach(l=>l.end=Math.min(l.end??state.duration,state.duration));syncComposition();renderLayers();pushHistory();toast('Composição atualizada')};

function interpolate(l,time){if(!l.keyframes?.length)return l;const keys=[...l.keyframes].sort((a,b)=>a.time-b.time);const before=[...keys].reverse().find(k=>k.time<=time),after=keys.find(k=>k.time>=time);if(!before&&!after)return l;const a=before||after,b=after||before;if(a===b)return {...l,...a.values};const p=(time-a.time)/(b.time-a.time);const values={};for(const k of ['x','y','scale','rotation','opacity'])values[k]=a.values[k]+(b.values[k]-a.values[k])*p;return {...l,...values}}
setTime=function(t){originalSetTime(t);state.layers.forEach(l=>{const e=$(`.layer[data-id="${l.id}"]`);if(e)applyStyle(e,interpolate(l,state.time));const v=e?.querySelector('video,audio');if(v){const hasSolo=state.layers.some(x=>(x.type==='video'||x.type==='audio')&&x.solo);v.muted=!!l.muted||(hasSolo&&!l.solo);v.volume=Math.min(1,(l.volume??100)/100);v.playbackRate=l.speed||1;if(state.playing&&(state.time<(l.start||0)||state.time>(l.end??state.duration)))v.pause()}})};
$('#addKeyframe').onclick=()=>{const l=selected();if(!l)return;l.keyframes=l.keyframes||[];l.keyframes=l.keyframes.filter(k=>Math.abs(k.time-state.time)>.02);l.keyframes.push({time:state.time,values:{x:l.x,y:l.y,scale:l.scale,rotation:l.rotation,opacity:l.opacity}});renderTimeline();pushHistory();toast(`Keyframe em ${state.time.toFixed(2)}s`)};

const advancedFields={Start:'start',End:'end',AnchorX:'anchorX',AnchorY:'anchorY',CropX:'cropX',CropY:'cropY',FitMode:'fitMode',Visible:'visible',Locked:'locked',FlipX:'flipX',FlipY:'flipY',Blend:'blend',Radius:'radius',Stroke:'stroke',StrokeColor:'strokeColor',Font:'font',FontSize:'fontSize',Mask:'mask'};
for(const [id,key] of Object.entries(advancedFields)){const el=$('#prop'+id);el.oninput=e=>{const l=selected();if(!l)return;l[key]=el.type==='checkbox'?el.checked:(el.type==='range'||el.type==='number'?+el.value:el.value);updateSelected();syncAdvancedProps();markDirty()}}
function syncAdvancedProps(){const l=selected();if(!l)return;for(const [id,key] of Object.entries(advancedFields)){const el=$('#prop'+id);if(el.type==='checkbox')el.checked=key==='visible'?l[key]!==false:!!l[key];else el.value=l[key]??({end:state.duration,fontSize:42,anchorX:50,anchorY:50,fitMode:'contain'}[key]??0);const out=$('#out'+id);if(out)out.value=el.value+(key==='radius'||key==='fontSize'?'px':'') }}
const oldSyncProps=syncProps;syncProps=function(){oldSyncProps();syncAdvancedProps()};

function requireVideo(){const l=selected();if(!l||!['video','audio'].includes(l.type)){toast('Selecione uma camada de vídeo ou áudio');return null}return l}
function clampTrim(l){l.start=Math.max(0,Math.min(l.start||0,state.duration-.01));l.end=Math.max(l.start+.01,Math.min(l.end??state.duration,state.duration));l.sourceIn=Math.max(0,l.sourceIn||0);l.sourceOut=Math.min(l.mediaDuration||Infinity,l.sourceOut??l.mediaDuration??state.duration)}
$('#setInPoint').onclick=()=>{const l=requireVideo();if(!l)return;const old=l.start||0;l.sourceIn=(l.sourceIn||0)+Math.max(0,state.time-old)*(l.speed||1);l.start=state.time;clampTrim(l);renderLayers();selectLayer(l.id);pushHistory();toast('Entrada definida')};
$('#setOutPoint').onclick=()=>{const l=requireVideo();if(!l)return;l.sourceOut=(l.sourceIn||0)+Math.max(0,state.time-(l.start||0))*(l.speed||1);l.end=state.time;clampTrim(l);renderLayers();selectLayer(l.id);pushHistory();toast('Saída definida')};
$('#splitAtPlayhead').onclick=()=>{const l=requireVideo();if(!l||state.time<=l.start||state.time>=l.end)return toast('Posicione o cursor dentro do clipe');const cutSource=(l.sourceIn||0)+(state.time-l.start)*(l.speed||1),oldEnd=l.end,oldSourceOut=l.sourceOut;const right={...l,id:uid++,name:l.name+' · parte 2',start:state.time,end:oldEnd,sourceIn:cutSource,sourceOut:oldSourceOut,keyframes:(l.keyframes||[]).filter(k=>k.time>=state.time)};l.end=state.time;l.sourceOut=cutSource;l.keyframes=(l.keyframes||[]).filter(k=>k.time<=state.time);state.layers.splice(state.layers.indexOf(l)+1,0,right);renderLayers();selectLayer(right.id);pushHistory();toast('Clipe dividido')};
$('#resetTrim').onclick=()=>{const l=requireVideo();if(!l)return;l.start=0;l.sourceIn=0;l.sourceOut=l.mediaDuration||state.duration;l.end=Math.min(state.duration,(l.sourceOut-l.sourceIn)/(l.speed||1));renderLayers();selectLayer(l.id);pushHistory();toast('Corte restaurado')};
for(const [id,key] of [['propSpeed','speed'],['propVolume','volume'],['propFadeIn','fadeIn'],['propFadeOut','fadeOut'],['propMuted','muted']])$('#'+id).oninput=e=>{const l=requireVideo();if(!l)return;l[key]=e.target.type==='checkbox'?e.target.checked:+e.target.value;if(key==='speed')$('#outSpeed').value=l.speed.toFixed(2)+'×';if(key==='volume')$('#outVolume').value=l.volume+'%';const v=$(`.layer[data-id="${l.id}"] video`);if(v){v.muted=l.muted;v.volume=Math.min(1,l.volume/100);v.playbackRate=l.speed}markDirty()};

const effectKeys={Brightness:'brightness',Contrast:'contrast',Saturation:'saturation',Hue:'hue',Blur:'blur',Grayscale:'grayscale',Sepia:'sepia',Invert:'invert'};
function buildFilter(l){const f=l.effects||{};return `brightness(${(f.brightness??100)/100}) contrast(${(f.contrast??100)/100}) saturate(${(f.saturation??100)/100}) hue-rotate(${f.hue||0}deg) blur(${f.blur||0}px) grayscale(${(f.grayscale||0)/100}) sepia(${(f.sepia||0)/100}) invert(${(f.invert||0)/100})`}
for(const [id,key] of Object.entries(effectKeys))$('#fx'+id).oninput=e=>{const l=selected();if(!l)return toast('Selecione uma camada');l.effects=l.effects||{};l.effects[key]=+e.target.value;l.filter=buildFilter(l);$('#out'+id).value=e.target.value+(key==='hue'?'°':key==='blur'?'px':'%');updateSelected();markDirty()};
$('#resetEffects').onclick=()=>{const l=selected();if(!l)return;l.effects={brightness:100,contrast:100,saturation:100,hue:0,blur:0,grayscale:0,sepia:0,invert:0};l.filter=buildFilter(l);syncAdvancedProps();updateSelected();markDirty();toast('Efeitos restaurados')};
$$('[data-effect]').forEach(b=>b.onclick=()=>{const l=selected();if(!l)return toast('Selecione uma camada');const presets={'none':{},'grayscale(1)':{grayscale:100},'sepia(.8)':{sepia:80},'blur(3px)':{blur:3},'contrast(1.5)':{contrast:150},'saturate(1.8)':{saturation:180},'brightness(1.35)':{brightness:135},'hue-rotate(90deg)':{hue:90},'invert(1)':{invert:100},'drop-shadow(8px 8px 8px #000)':{contrast:115,brightness:85}};l.effects={brightness:100,contrast:100,saturation:100,hue:0,blur:0,grayscale:0,sepia:0,invert:0,...presets[b.dataset.effect]};l.filter=buildFilter(l);syncAdvancedProps();updateSelected();markDirty();toast('Efeito aplicado')});

const previousSyncAdvancedProps=syncAdvancedProps;syncAdvancedProps=function(){previousSyncAdvancedProps();const l=selected();if(!l)return;$('#propSpeed').value=l.speed||1;$('#outSpeed').value=(l.speed||1).toFixed(2)+'×';$('#propVolume').value=l.volume??100;$('#outVolume').value=(l.volume??100)+'%';$('#propFadeIn').value=l.fadeIn||0;$('#propFadeOut').value=l.fadeOut||0;$('#propMuted').checked=!!l.muted;for(const [id,key] of Object.entries(effectKeys)){const value=l.effects?.[key]??(key==='brightness'||key==='contrast'||key==='saturation'?100:0);$('#fx'+id).value=value;$('#out'+id).value=value+(key==='hue'?'°':key==='blur'?'px':'%')}};

function moveSelected(delta){const i=state.layers.findIndex(l=>l.id===state.selected),j=i+delta;if(i<0||j<0||j>=state.layers.length)return;[state.layers[i],state.layers[j]]=[state.layers[j],state.layers[i]];renderLayers();selectLayer(state.selected);pushHistory()}
$('#moveLayerUp').onclick=()=>moveSelected(1);$('#moveLayerDown').onclick=()=>moveSelected(-1);
$('#groupLayer').onclick=()=>{const l=selected();if(!l)return;l.group=l.group?null:`Grupo ${Date.now().toString().slice(-4)}`;l.name=l.group?`${l.group} · ${l.name}`:l.name.replace(/^Grupo \d+ · /,'');renderTimeline();pushHistory();toast(l.group?'Camada agrupada':'Grupo removido')};

renderTimeline=function(){const t=$('#timeline');t.querySelectorAll('.track,.timeline-empty').forEach(e=>e.remove());if(!state.layers.length){const e=document.createElement('div');e.className='timeline-empty';e.textContent='Adicione uma camada para começar';t.prepend(e)}state.layers.slice().reverse().forEach(l=>{const row=document.createElement('div');row.className='track';const start=(l.start||0)/state.duration*100,end=(l.end??state.duration)/state.duration*100;const dots=(l.keyframes||[]).map(k=>`<i class="key-dot" style="left:${k.time/state.duration*100}%"></i>`).join('');row.innerHTML=`<div class="track-name"><button data-vis title="Visibilidade">${l.visible===false?'○':'●'}</button><button data-lock title="Bloqueio">${l.locked?'🔒':'🔓'}</button><span class="layer-title">${l.mask?'◩ ':''}${escapeHtml(l.name)}</span></div><div class="clip" style="margin-left:${start}%;width:${Math.max(1,end-start)}%;opacity:${l.visible===false?.35:1}">${l.type==='audio'?'♫ canal':escapeHtml(l.type)}${dots}</div>`;row.onclick=()=>selectLayer(l.id);row.querySelector('[data-vis]').onclick=e=>{e.stopPropagation();l.visible=l.visible===false;renderLayers();selectLayer(l.id);markDirty()};row.querySelector('[data-lock]').onclick=e=>{e.stopPropagation();l.locked=!l.locked;renderTimeline();selectLayer(l.id);markDirty()};t.insertBefore(row,$('#playhead'))});renderAudioMixer()};

function renderAudioMixer(){const box=$('#audioMixer');if(!box)return;const channels=state.layers.filter(l=>l.type==='audio'||l.type==='video');if(!channels.length){box.innerHTML='<div class="empty">Importe áudio ou um vídeo com som</div>';return}box.innerHTML='';for(const l of channels){const card=document.createElement('div');card.className='audio-channel',rawVolume=Number(l.volume),rawPan=Number(l.pan),volume=Math.max(0,Math.min(200,Number.isFinite(rawVolume)?rawVolume:100)),pan=Math.max(-100,Math.min(100,Number.isFinite(rawPan)?rawPan:0));card.innerHTML=`<strong>${l.type==='video'?'🎬':'♫'} ${escapeHtml(l.name)}</strong><label>Volume ${volume}%<input data-volume type="range" min="0" max="200" value="${volume}"></label><label>Pan L/R ${pan}<input data-pan type="range" min="-100" max="100" value="${pan}"></label><label>Fonte<select data-channel><option value="stereo">Estéreo</option><option value="left">Somente canal esquerdo</option><option value="right">Somente canal direito</option></select></label><label><input data-mute type="checkbox" ${l.muted?'checked':''}> Mudo</label><label><input data-solo type="checkbox" ${l.solo?'checked':''}> Solo</label>`;card.onclick=()=>selectLayer(l.id);card.querySelector('[data-channel]').value=['stereo','left','right'].includes(l.audioChannel)?l.audioChannel:'stereo';card.querySelector('[data-volume]').oninput=e=>{l.volume=+e.target.value;renderAudioMixer();markDirty()};card.querySelector('[data-pan]').oninput=e=>{l.pan=+e.target.value;renderAudioMixer();markDirty()};card.querySelector('[data-channel]').onchange=e=>{l.audioChannel=e.target.value;markDirty()};card.querySelector('[data-mute]').onchange=e=>{l.muted=e.target.checked;renderLayers();markDirty()};card.querySelector('[data-solo]').onchange=e=>{l.solo=e.target.checked;renderAudioMixer();markDirty()};box.append(card)}}

$('#startDrawing').onclick=()=>{state.drawing=!state.drawing;$('#stage').classList.toggle('drawing',state.drawing);$('#startDrawing').textContent=state.drawing?'Desenho ativo — arraste no palco':'Iniciar desenho';toast(state.drawing?'Modo desenho ativo':'Modo desenho encerrado')};
let drawPoints=[];
$('#stage').addEventListener('pointerdown',e=>{if(!state.drawing||e.target!==$('#stage'))return;e.preventDefault();drawPoints=[];const r=$('#stage').getBoundingClientRect();const point=x=>drawPoints.push([(x.clientX-r.left)/r.width*640,(x.clientY-r.top)/r.height*360]);point(e);const move=x=>point(x);const up=()=>{removeEventListener('pointermove',move);removeEventListener('pointerup',up);if(drawPoints.length<2)return;const c=document.createElement('canvas');c.width=640;c.height=360;const g=c.getContext('2d');g.strokeStyle=$('#brushColor').value;g.lineWidth=+$('#brushSize').value;g.lineCap='round';g.lineJoin='round';g.beginPath();drawPoints.forEach((p,i)=>i?g.lineTo(...p):g.moveTo(...p));g.stroke();addLayer('drawing',c.toDataURL(),'Desenho livre');state.drawing=false;$('#stage').classList.remove('drawing');$('#startDrawing').textContent='Iniciar desenho'};addEventListener('pointermove',move);addEventListener('pointerup',up)});
$('#clearDrawing').onclick=()=>{const l=selected();if(l?.type==='drawing'){$('#deleteLayer').click()}else toast('Selecione uma camada de desenho')};

const oldRenderLayers=renderLayers;renderLayers=function(){oldRenderLayers();state.layers.forEach(l=>{if(l.type==='drawing'){const e=$(`.layer[data-id="${l.id}"]`);if(e&&typeof l.content==='string'&&l.content.startsWith('data:image/')){e.replaceChildren();const image=document.createElement('img');image.src=l.content;image.style.width='640px';image.style.height='360px';e.append(image);applyStyle(e,l)}}})};

function projectData(){return{format:'motion-livre',version:4,name:$('#projectName').value,aspect:$('#aspect').value,duration:state.duration,composition:state.composition,markers:state.markers||[],layers:state.layers.map(l=>({...l,content:['image','video','audio'].includes(l.type)?'':l.content}))}}
function downloadJson(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(projectData(),null,2)],{type:'application/json'}));a.download=($('#projectName').value||'projeto')+'.motion.json';a.click();toast('Projeto JSON exportado')}
$('#exportProject').onclick=downloadJson;$('#menuExport').onclick=downloadJson;
$('#importProject').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>50*1024*1024)throw new Error('Projeto acima de 50 MB');const d=JSON.parse(await f.text());if(!Array.isArray(d.layers)||d.layers.length>5000)throw new Error('Quantidade de camadas inválida');$('#projectName').value=d.name||'Projeto importado';$('#aspect').value=d.aspect||'16/9';state.duration=d.duration||10;state.composition=d.composition||state.composition;state.layers=d.layers.map(l=>({...l,id:uid++,keyframes:Array.isArray(l.keyframes)?l.keyframes.slice(0,10000):[]}));syncComposition();renderLayers();pushHistory();toast('Projeto importado')}catch{toast('Arquivo de projeto inválido')}};
$('#menuImport').onclick=()=>$('#importProject').click();
$('#projectFile').onclick=()=>$('#projectMenu').hidden=!$('#projectMenu').hidden;
$('#menuFeatures').onclick=()=>{$('#featureModal').hidden=false;$('#projectMenu').hidden=true};$('#closeFeatures').onclick=()=>$('#featureModal').hidden=true;
$('#featureGrid').className='feature-grid';$('#featureGrid').innerHTML=Object.entries(featureMap).map(([title,items])=>`<section class="feature-card"><h3>${title}</h3><ul>${items.map(x=>`<li>${x}</li>`).join('')}</ul></section>`).join('');

document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();$('#undoBtn').click()}if(e.ctrlKey&&e.key.toLowerCase()==='y'){e.preventDefault();$('#redoBtn').click()}if(e.key==='Delete'&&state.selected)$('#deleteLayer').click();if(e.code==='Space'&&!['INPUT','TEXTAREA'].includes(e.target.tagName)){e.preventDefault();$('#playBtn').click()}});
syncComposition();pushHistory();renderLayers();
