/* Ferramentas profissionais: timeline editável, curvas, waveform, parenting e efeitos. */
(function(){
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const mediaTypes=new Set(['video','audio']);
  state.timelineZoom=state.timelineZoom||1;state.snapTimeline=state.snapTimeline!==false;state.markers=state.markers||[];state.showMotionPath=true;state.selectedIds=state.selectedIds||new Set();state.maskEditing=false;state.pathEditing=false;

  function ensureDefaults(l){Object.assign(l,{visible:l.visible!==false,locked:!!l.locked,anchorX:l.anchorX??50,anchorY:l.anchorY??50,depth:l.depth||0,perspective:l.perspective||1200,cropX:l.cropX||0,cropY:l.cropY||0,fillType:l.fillType||'solid',gradientColor:l.gradientColor||'#7758ff',gradientAngle:l.gradientAngle||0,maskMode:l.maskMode||(l.mask?'inset':'none'),maskPoints:l.maskPoints||[],easing:l.easing||'linear',parentId:l.parentId||null,transitionIn:l.transitionIn||'none',transitionOut:l.transitionOut||'none',transitionDuration:l.transitionDuration??.5,reverse:!!l.reverse,effectOrder:l.effectOrder||['rgb','brightness','contrast','saturation','hue','blur','grayscale','sepia','invert','sharpen','motionBlur','glow'],effects:{brightness:100,contrast:100,saturation:100,hue:0,blur:0,grayscale:0,sepia:0,invert:0,glow:0,vignette:0,sharpen:0,chromaTolerance:0,motionBlur:0,redGain:100,greenGain:100,blueGain:100,...l.effects}});return l}
  state.layers.forEach(ensureDefaults);
  const priorAddLayer=addLayer;
  addLayer=function(type,content,name){return ensureDefaults(priorAddLayer(type,content,name))};

  function easeValue(p,type){p=Math.max(0,Math.min(1,p));if(type==='ease-in')return p*p*p;if(type==='ease-out')return 1-Math.pow(1-p,3);if(type==='ease-in-out')return p<.5?4*p*p*p:1-Math.pow(-2*p+2,3)/2;if(type==='bounce'){const n=7.5625,d=2.75;if(p<1/d)return n*p*p;if(p<2/d)return n*(p-=1.5/d)*p+.75;if(p<2.5/d)return n*(p-=2.25/d)*p+.9375;return n*(p-=2.625/d)*p+.984375}return p}
  function interpolateProperty(l,prop,time){const keys=(l.keyframes||[]).filter(k=>Number.isFinite(k.values?.[prop])).sort((a,b)=>a.time-b.time);if(!keys.length)return l[prop];const before=[...keys].reverse().find(k=>k.time<=time),after=keys.find(k=>k.time>=time);if(!before)return after.values[prop];if(!after)return before.values[prop];if(before===after)return before.values[prop];const p=easeValue((time-before.time)/(after.time-before.time),after.easing||l.easing);return before.values[prop]+(after.values[prop]-before.values[prop])*p}
  function localTransform(source,time){const l={...source};for(const prop of ['x','y','depth','scale','rotation','opacity'])l[prop]=interpolateProperty(source,prop,time);const start=l.start||0,end=l.end??state.duration,d=Math.max(.01,Math.min(l.transitionDuration||.5,(end-start)/2));const intro=Math.max(0,Math.min(1,(time-start)/d)),outro=Math.max(0,Math.min(1,(end-time)/d));const transition=(kind,p,isIn)=>{if(kind==='fade')l.opacity*=p;if(kind==='zoom')l.scale*=.65+.35*p;if(kind==='slide-left')l.x+=(isIn?-1:1)*(1-p)*35;if(kind==='slide-right')l.x+=(isIn?1:-1)*(1-p)*35};transition(l.transitionIn,intro,true);transition(l.transitionOut,outro,false);return l}
  function resolvedTransform(source,time,seen=new Set()){const l=localTransform(source,time);if(!l.parentId||seen.has(l.id))return l;seen.add(l.id);const parent=state.layers.find(x=>x.id===l.parentId);if(!parent)return l;const p=resolvedTransform(parent,time,seen);l.x=p.x+(l.x-50)*(p.scale/100);l.y=p.y+(l.y-50)*(p.scale/100);l.scale=l.scale*p.scale/100;l.rotation+=p.rotation;l.opacity=l.opacity*p.opacity/100;return l}
  interpolate=function(source,time){const l=resolvedTransform(ensureDefaults(source),time);if(source.type!=='camera'){const camera=[...state.layers].reverse().find(x=>x.type==='camera'&&x.visible!==false&&time>=(x.start||0)&&time<=(x.end??state.duration));if(camera){const c=localTransform(camera,time),zoom=(c.scale||100)/100,perspective=Math.max(300,c.perspective||1200),depthScale=Math.max(.1,Math.min(10,perspective/(perspective-(l.depth||0))));l.x=50+(l.x-c.x)*zoom;l.y=50+(l.y-c.y)*zoom;l.scale*=zoom*depthScale;l.rotation-=c.rotation||0}}return l};

  function colorFilter(l){const id=`ml-color-${l.id}`,fx=l.effects||{},values=`${(fx.redGain??100)/100} 0 0 0 0 0 ${(fx.greenGain??100)/100} 0 0 0 0 0 ${(fx.blueGain??100)/100} 0 0 0 0 1 0`;let defs=$('#motionColorFilters');if(!defs){defs=document.createElementNS('http://www.w3.org/2000/svg','svg');defs.id='motionColorFilters';defs.style.display='none';document.body.append(defs)}let filter=defs.querySelector(`#${id}`);if(!filter){filter=document.createElementNS(defs.namespaceURI,'filter');filter.id=id;const matrix=document.createElementNS(defs.namespaceURI,'feColorMatrix');matrix.setAttribute('type','matrix');filter.append(matrix);defs.append(filter)}filter.firstElementChild.setAttribute('values',values);return `url(#${id})`}
  buildFilter=function(l){ensureDefaults(l);const fx=l.effects||{},rgb=(fx.redGain??100)!==100||(fx.greenGain??100)!==100||(fx.blueGain??100)!==100,filters={rgb:rgb?colorFilter(l):'',brightness:`brightness(${(fx.brightness??100)/100})`,contrast:`contrast(${(fx.contrast??100)/100})`,saturation:`saturate(${(fx.saturation??100)/100})`,hue:`hue-rotate(${fx.hue||0}deg)`,blur:`blur(${fx.blur||0}px)`,grayscale:`grayscale(${(fx.grayscale||0)/100})`,sepia:`sepia(${(fx.sepia||0)/100})`,invert:`invert(${(fx.invert||0)/100})`,sharpen:fx.sharpen?`contrast(${1+fx.sharpen/250})`:'',motionBlur:fx.motionBlur?`blur(${fx.motionBlur/3}px)`:'',glow:fx.glow?`drop-shadow(0 0 ${Math.max(1,fx.glow/3)}px ${l.glowColor||'#ffffff'})`:''};return l.effectOrder.map(key=>filters[key]).filter(Boolean).join(' ')||'none'};
  const inheritedApplyStyle=applyStyle;
  applyStyle=function(e,l){ensureDefaults(l);l.filter=buildFilter(l);inheritedApplyStyle(e,l);e.classList.toggle('null-layer',l.type==='null');e.classList.toggle('camera-layer',l.type==='camera');e.classList.toggle('vignette',(l.effects?.vignette||0)>0);e.style.setProperty('--vignette',String((l.effects?.vignette||0)/100));if(l.fillType==='linear')e.style.background=`linear-gradient(${l.gradientAngle||0}deg,${l.color},${l.gradientColor})`;else if(l.fillType==='radial')e.style.background=`radial-gradient(circle,${l.color},${l.gradientColor})`;if(l.maskMode==='circle')e.style.clipPath='circle(48%)';else if(l.maskMode==='ellipse')e.style.clipPath='ellipse(48% 42%)';else if(l.maskMode==='polygon'&&l.maskPoints.length>2)e.style.clipPath=`polygon(${l.maskPoints.map(p=>`${p[0]}% ${p[1]}%`).join(',')})`;else if(l.maskMode==='inset')e.style.clipPath=`inset(${l.cropY||0}% ${l.cropX||0}% round ${l.radius||0}px)`;else e.style.clipPath=`inset(${l.cropY||0}% ${l.cropX||0}%)`};

  async function waveformFromFile(file){try{const context=new AudioContext(),buffer=await context.decodeAudioData(await file.arrayBuffer()),data=buffer.getChannelData(0),count=180,step=Math.max(1,Math.floor(data.length/count)),points=[];for(let i=0;i<count;i++){let peak=0;for(let j=0;j<step;j++)peak=Math.max(peak,Math.abs(data[i*step+j]||0));points.push(Math.round(peak*1000)/1000)}await context.close();return points}catch{return []}}
  const priorImportMedia=importMedia;
  importMedia=async function(file){const before=new Set(state.layers.map(l=>l.id));await priorImportMedia(file);const layer=state.layers.find(l=>!before.has(l.id));if(layer&&file.type.startsWith('video')){layer.waveform=await waveformFromFile(file);renderTimeline()}};
  $('#audioInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;const url=URL.createObjectURL(file),probe=document.createElement('audio');probe.src=url;const duration=await new Promise(resolve=>{probe.onloadedmetadata=()=>resolve(Number.isFinite(probe.duration)?probe.duration:state.duration);probe.onerror=()=>resolve(state.duration)}),layer=addLayer('audio',url,file.name);Object.assign(layer,{sourcePath:motionDesktop?.getPathForFile?.(file)||'',mediaDuration:duration,sourceIn:0,sourceOut:duration,start:0,end:Math.min(duration,state.duration),waveform:await waveformFromFile(file)});renderLayers();selectLayer(layer.id);switchPanel('audio');markDirty()};

  function snapTime(value,ignore){let v=Math.max(0,Math.min(state.duration,value));if(!state.snapTimeline)return v;const points=[0,state.duration,state.time,...state.markers];for(const l of state.layers)if(l!==ignore)points.push(l.start||0,l.end??state.duration);let nearest=points[0],distance=Math.abs(v-nearest);for(const p of points){const d=Math.abs(v-p);if(d<distance){nearest=p;distance=d}}return distance<Math.max(.04,state.duration/(700*state.timelineZoom)*8)?nearest:Math.round(v*20)/20}
  function drawWave(canvas,points){if(!points?.length)return;const g=canvas.getContext('2d'),w=canvas.width=canvas.clientWidth*devicePixelRatio,h=canvas.height=canvas.clientHeight*devicePixelRatio;g.clearRect(0,0,w,h);g.strokeStyle='#e5ddff';g.lineWidth=1;g.beginPath();points.forEach((p,i)=>{const x=i/(points.length-1)*w,y=p*h*.44;g.moveTo(x,h/2-y);g.lineTo(x,h/2+y)});g.stroke()}
  function beginClipEdit(event,layer,mode,clip,laneWidth){event.preventDefault();event.stopPropagation();selectLayer(layer.id);const x0=event.clientX,start0=layer.start||0,end0=layer.end??state.duration,in0=layer.sourceIn||0,out0=layer.sourceOut??layer.mediaDuration??state.duration,duration=end0-start0,secondsPerPixel=state.duration/laneWidth;const move=e=>{const delta=(e.clientX-x0)*secondsPerPixel;if(mode==='move'){const next=snapTime(start0+delta,layer),shift=Math.max(-start0,Math.min(state.duration-end0,next-start0));layer.start=start0+shift;layer.end=end0+shift}else if(mode==='left'){const next=snapTime(start0+delta,layer);layer.start=Math.min(end0-.03,next);layer.sourceIn=Math.max(0,in0+(layer.start-start0)*(layer.speed||1))}else{const next=snapTime(end0+delta,layer);layer.end=Math.max(start0+.03,next);layer.sourceOut=Math.min(layer.mediaDuration||Infinity,out0+(layer.end-end0)*(layer.speed||1))}clip.style.left=`${layer.start/state.duration*laneWidth}px`;clip.style.width=`${Math.max(4,(layer.end-layer.start)/state.duration*laneWidth)}px`;syncProps();setTime(state.time)};const up=()=>{removeEventListener('pointermove',move);removeEventListener('pointerup',up);renderTimeline();pushHistory();markDirty()};addEventListener('pointermove',move);addEventListener('pointerup',up)}
  renderTimeline=function(){
    const timeline=$('#timeline');timeline.querySelectorAll('.track,.timeline-empty,.timeline-marker').forEach(e=>e.remove());const laneWidth=Math.max(520,(timeline.clientWidth-240)*state.timelineZoom);
    if(!state.layers.length){const empty=document.createElement('div');empty.className='timeline-empty';empty.textContent='Adicione uma camada para começar';timeline.prepend(empty)}
    for(const layer of [...state.layers].reverse()){
      ensureDefaults(layer);const row=document.createElement('div');row.className='track'+(layer.id===state.selected?' selected-track':'');row.style.width=`${240+laneWidth}px`;row.style.gridTemplateColumns=`240px ${laneWidth}px`;
      const name=document.createElement('div');name.className='track-name';name.innerHTML=`<button data-multi title="Marcar para precomposição">${state.selectedIds.has(layer.id)?'☑':'☐'}</button><button data-vis title="Visibilidade">${layer.visible?'●':'○'}</button><button data-lock title="Bloqueio">${layer.locked?'🔒':'🔓'}</button>${mediaTypes.has(layer.type)?`<button data-mute title="Áudio">${layer.muted?'🔇':'🔊'}</button>`:''}<span class="layer-title">${esc(layer.name)}</span>`;
      const lane=document.createElement('div');lane.className='track-lane';const clip=document.createElement('div');clip.className='clip pro-clip';clip.style.left=`${(layer.start||0)/state.duration*laneWidth}px`;clip.style.width=`${Math.max(4,((layer.end??state.duration)-(layer.start||0))/state.duration*laneWidth)}px`;clip.style.opacity=layer.visible?1:.35;clip.innerHTML=`<i class="clip-handle left"></i>${layer.waveform?.length?'<canvas class="clip-waveform"></canvas>':''}<span class="clip-label">${layer.type==='audio'?'♫':layer.type==='video'?'🎬':'◆'} ${esc(layer.name)}</span><i class="clip-handle right"></i>${(layer.keyframes||[]).map(k=>`<i class="key-dot" style="left:${(k.time-(layer.start||0))/Math.max(.01,(layer.end??state.duration)-(layer.start||0))*100}%"></i>`).join('')}`;
      lane.append(clip);row.append(name,lane);timeline.insertBefore(row,$('#playhead'));row.onclick=()=>selectLayer(layer.id);lane.onclick=e=>{if(e.target===lane){selectLayer(layer.id);setTime((e.offsetX/laneWidth)*state.duration)}};
      name.querySelector('[data-multi]').onclick=e=>{e.stopPropagation();state.selectedIds.has(layer.id)?state.selectedIds.delete(layer.id):state.selectedIds.add(layer.id);renderTimeline()};name.querySelector('[data-vis]').onclick=e=>{e.stopPropagation();layer.visible=!layer.visible;renderLayers();selectLayer(layer.id);markDirty()};name.querySelector('[data-lock]').onclick=e=>{e.stopPropagation();layer.locked=!layer.locked;renderTimeline();markDirty()};name.querySelector('[data-mute]')?.addEventListener('click',e=>{e.stopPropagation();layer.muted=!layer.muted;renderTimeline();renderAudioMixer();markDirty()});clip.onpointerdown=e=>{if(layer.locked)return toast('Camada bloqueada');const mode=e.target.classList.contains('left')?'left':e.target.classList.contains('right')?'right':'move';beginClipEdit(e,layer,mode,clip,laneWidth)};requestAnimationFrame(()=>drawWave(clip.querySelector('canvas'),layer.waveform));
    }
    for(const marker of state.markers){const m=document.createElement('i');m.className='timeline-marker';m.style.left=`${240+marker/state.duration*laneWidth}px`;timeline.append(m)}renderAudioMixer();
  };
  const timelineSetTime=setTime;
  setTime=function(t){timelineSetTime(t);const timeline=$('#timeline'),laneWidth=Math.max(520,(timeline.clientWidth-240)*state.timelineZoom);$('#playhead').style.left=`${240+state.time/state.duration*laneWidth}px`;for(const l of state.layers.filter(x=>x.reverse&&mediaTypes.has(x.type))){const media=$(`.layer[data-id="${l.id}"] video,.layer[data-id="${l.id}"] audio`);if(!media)continue;const sourceTime=Math.max(l.sourceIn||0,(l.sourceOut??l.mediaDuration??0)-Math.max(0,state.time-(l.start||0))*(l.speed||1));media.pause();if(Math.abs(media.currentTime-sourceTime)>.04)media.currentTime=sourceTime}};
  $('#timelineZoom').oninput=e=>{state.timelineZoom=+e.target.value;renderTimeline();setTime(state.time)};$('#snapTimeline').onchange=e=>state.snapTimeline=e.target.checked;$('#addMarker').onclick=()=>{state.markers.push(state.time);state.markers=[...new Set(state.markers.map(x=>+x.toFixed(3)))].sort((a,b)=>a-b);renderTimeline();markDirty()};$('#clearMarkers').onclick=()=>{state.markers=[];renderTimeline();markDirty()};
  const newProjectAction=$('#newProject').onclick;$('#newProject').onclick=e=>{state.markers=[];state.selectedIds.clear();state.maskEditing=false;newProjectAction.call($('#newProject'),e);renderTimeline()};

  function drawEasing(){const c=$('#easingGraph'),g=c.getContext('2d'),type=selected()?.easing||'linear';g.clearRect(0,0,c.width,c.height);g.strokeStyle='#303642';for(let i=1;i<5;i++){g.beginPath();g.moveTo(i*c.width/5,0);g.lineTo(i*c.width/5,c.height);g.stroke()}g.strokeStyle='#9d7cff';g.lineWidth=3;g.beginPath();for(let i=0;i<=100;i++){const p=i/100,x=10+p*(c.width-20),y=c.height-10-easeValue(p,type)*(c.height-20);i?g.lineTo(x,y):g.moveTo(x,y)}g.stroke()}
  function syncProProps(){const l=selected();if(!l)return;ensureDefaults(l);$('#propDepth').value=l.depth;$('#outDepth').value=l.depth;$('#propPerspective').value=l.perspective;$('#outPerspective').value=l.perspective;$('#propEasing').value=l.easing;$('#propTransitionIn').value=l.transitionIn;$('#propTransitionOut').value=l.transitionOut;$('#propTransitionDuration').value=l.transitionDuration;$('#propReverse').checked=l.reverse;$('#propFillType').value=l.fillType;$('#propGradientColor').value=l.gradientColor;$('#propGradientAngle').value=l.gradientAngle;$('#outGradientAngle').value=l.gradientAngle+'°';$('#propMaskMode').value=l.maskMode;$('#fxGlowColor').value=l.glowColor||'#ffffff';$('#fxChromaColor').value=l.chromaColor||'#00ff00';for(const [id,key] of Object.entries(proEffectFields)){const value=l.effects?.[key]??(key.endsWith('Gain')?100:0);$('#fx'+id).value=value;$('#out'+id).value=value+(key==='motionBlur'?'px':'%')}const parent=$('#propParent'),current=String(l.parentId||'');parent.innerHTML='<option value="">Nenhuma</option>'+state.layers.filter(x=>x.id!==l.id).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');parent.value=current;drawEasing();renderEffectStack();renderMotionPath()}
  const priorSyncProps=syncProps;syncProps=function(){priorSyncProps();syncProProps()};
  for(const [id,key,type] of [['propDepth','depth','number'],['propPerspective','perspective','number'],['propEasing','easing','value'],['propTransitionIn','transitionIn','value'],['propTransitionOut','transitionOut','value'],['propTransitionDuration','transitionDuration','number'],['propReverse','reverse','checked'],['propFillType','fillType','value'],['propGradientColor','gradientColor','value'],['propGradientAngle','gradientAngle','number'],['propMaskMode','maskMode','value'],['propParent','parentId','parent']])$('#'+id).oninput=e=>{const l=selected();if(!l)return;l[key]=type==='checked'?e.target.checked:type==='number'?+e.target.value:type==='parent'?(+e.target.value||null):e.target.value;updateSelected();syncProProps();renderLayers();selectLayer(l.id);markDirty()};
  $('#addKeyframe').onclick=()=>{const l=selected();if(!l)return;const property=$('#keyframeProperty').value,values={};for(const key of property==='all'?['x','y','depth','scale','rotation','opacity']:[property])values[key]=l[key];l.keyframes=(l.keyframes||[]).filter(k=>!(Math.abs(k.time-state.time)<.02&&Object.keys(values).some(key=>key in (k.values||{}))));l.keyframes.push({time:state.time,values,easing:l.easing});renderTimeline();renderMotionPath();pushHistory();toast(`Keyframe de ${property==='all'?'transformação':property} criado`)};
  $('#addNullLayer').onclick=()=>{const l=addLayer('null','',`Controle nulo ${state.layers.filter(x=>x.type==='null').length+1}`);l.scale=100;renderLayers();selectLayer(l.id)};$('#addCameraLayer').onclick=()=>{for(const c of state.layers.filter(x=>x.type==='camera'))c.visible=false;const l=addLayer('camera','',`Câmera ${state.layers.filter(x=>x.type==='camera').length+1}`);Object.assign(l,{x:50,y:50,scale:100,perspective:1200});renderLayers();selectLayer(l.id)};$('#showMotionPath').onclick=()=>{state.showMotionPath=!state.showMotionPath;renderMotionPath();$('#showMotionPath').textContent=state.showMotionPath?'Ocultar caminho de movimento':'Exibir caminho de movimento'};
  $('#precomposeLayers').onclick=()=>{const children=state.layers.filter(l=>state.selectedIds.has(l.id));if(children.length<2)return toast('Marque pelo menos duas camadas na timeline');const cx=children.reduce((s,l)=>s+l.x,0)/children.length,cy=children.reduce((s,l)=>s+l.y,0)/children.length,controller=addLayer('null','',`Precomposição ${Date.now().toString().slice(-4)}`);Object.assign(controller,{x:cx,y:cy,start:Math.min(...children.map(l=>l.start||0)),end:Math.max(...children.map(l=>l.end??state.duration)),precomposition:true});for(const child of children){child.x=50+(child.x-cx);child.y=50+(child.y-cy);child.parentId=controller.id;child.precompGroup=controller.name}state.selectedIds.clear();renderLayers();selectLayer(controller.id);pushHistory();toast(`${children.length} camadas precompostas`)};

  function renderMotionPath(){document.querySelector('.motion-path')?.remove();const l=selected();if(!l||!state.showMotionPath)return;const points=(l.keyframes||[]).filter(k=>Number.isFinite(k.values?.x)&&Number.isFinite(k.values?.y)).sort((a,b)=>a.time-b.time);if(points.length<2)return;const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('motion-path');svg.setAttribute('viewBox','0 0 100 100');const poly=document.createElementNS(svg.namespaceURI,'polyline');poly.setAttribute('points',points.map(p=>`${p.values.x},${p.values.y}`).join(' '));svg.append(poly);for(const p of points){const dot=document.createElementNS(svg.namespaceURI,'circle');dot.setAttribute('cx',p.values.x);dot.setAttribute('cy',p.values.y);dot.setAttribute('r','1.4');svg.append(dot)}$('#stage').append(svg)}
  function renderMaskOverlay(){document.querySelector('.mask-path')?.remove();const l=selected(),el=l&&$(`.layer[data-id="${l.id}"]`);if(!l||!el||l.maskMode!=='polygon'||l.maskPoints.length<1)return;const stage=$('#stage').getBoundingClientRect(),rect=el.getBoundingClientRect(),svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('mask-path');svg.setAttribute('viewBox','0 0 100 100');const mapped=l.maskPoints.map(p=>[(rect.left-stage.left+rect.width*p[0]/100)/stage.width*100,(rect.top-stage.top+rect.height*p[1]/100)/stage.height*100]);const poly=document.createElementNS(svg.namespaceURI,'polygon');poly.setAttribute('points',mapped.map(p=>p.join(',')).join(' '));svg.append(poly);for(const p of mapped){const dot=document.createElementNS(svg.namespaceURI,'circle');dot.setAttribute('cx',p[0]);dot.setAttribute('cy',p[1]);dot.setAttribute('r','1.2');svg.append(dot)}$('#stage').append(svg)}
  $('#editMaskPoints').onclick=()=>{const l=selected();if(!l)return toast('Selecione uma camada');l.maskMode='polygon';state.maskEditing=!state.maskEditing;$('#editMaskPoints').textContent=state.maskEditing?'Clique no elemento · duplo clique encerra':'Editar máscara no palco';renderLayers();selectLayer(l.id)};$('#clearMaskPoints').onclick=()=>{const l=selected();if(!l)return;l.maskPoints=[];l.maskMode='none';state.maskEditing=false;renderLayers();selectLayer(l.id);markDirty()};$('#stage').addEventListener('pointerdown',e=>{if(!state.maskEditing)return;const l=selected(),el=l&&$(`.layer[data-id="${l.id}"]`);if(!el)return;e.preventDefault();e.stopPropagation();const r=el.getBoundingClientRect();l.maskPoints.push([Math.max(0,Math.min(100,(e.clientX-r.left)/r.width*100)),Math.max(0,Math.min(100,(e.clientY-r.top)/r.height*100))]);updateSelected();renderMaskOverlay();markDirty()},true);$('#stage').addEventListener('dblclick',e=>{if(!state.maskEditing)return;e.preventDefault();state.maskEditing=false;$('#editMaskPoints').textContent='Editar máscara no palco';pushHistory();toast('Máscara personalizada concluída')},true);

  function bezierPath(points){if(!points?.length)return'';if(points.length===1)return`M ${points[0][0]} ${points[0][1]}`;let d=`M ${points[0][0]} ${points[0][1]}`;for(let i=1;i<points.length-1;i++){const mid=[(points[i][0]+points[i+1][0])/2,(points[i][1]+points[i+1][1])/2];d+=` Q ${points[i][0]} ${points[i][1]} ${mid[0]} ${mid[1]}`}const last=points.at(-1);return d+` T ${last[0]} ${last[1]}`}
  function renderVectorPaths(){for(const l of state.layers.filter(x=>x.type==='path')){const e=$(`.layer[data-id="${l.id}"]`);if(!e)continue;e.classList.add('path-layer');e.innerHTML=`<svg viewBox="0 0 100 100" preserveAspectRatio="none"><path d="${bezierPath(l.pathPoints||[])}" fill="none" stroke="${l.color||'#fff'}" stroke-width="${Math.max(.3,l.stroke||1)}" stroke-linecap="round" stroke-linejoin="round"/></svg>`;applyStyle(e,l)}}
  $('#startBezierPath').onclick=()=>{let l=selected();if(!l||l.type!=='path'){l=addLayer('path','',`Caminho Bézier ${state.layers.filter(x=>x.type==='path').length+1}`);Object.assign(l,{x:50,y:50,scale:100,pathPoints:[],stroke:2})}state.pathEditing=!state.pathEditing;state.maskEditing=false;$('#startBezierPath').textContent=state.pathEditing?'Clique no palco · duplo clique encerra':'Caneta Bézier';renderLayers();selectLayer(l.id)};$('#stage').addEventListener('pointerdown',e=>{if(!state.pathEditing)return;const l=selected();if(!l||l.type!=='path')return;e.preventDefault();e.stopPropagation();const r=$('#stage').getBoundingClientRect();l.pathPoints.push([(e.clientX-r.left)/r.width*100,(e.clientY-r.top)/r.height*100]);renderVectorPaths();markDirty()},true);$('#stage').addEventListener('dblclick',e=>{if(!state.pathEditing)return;e.preventDefault();state.pathEditing=false;$('#startBezierPath').textContent='Caneta Bézier';pushHistory();toast('Caminho Bézier concluído')},true);
  function addTransformHandles(){const layer=selected(),el=layer&&$(`.layer[data-id="${layer.id}"]`);if(!el||layer.locked||layer.type==='audio')return;for(const kind of ['scale','rotate']){const h=document.createElement('i');h.className=`transform-handle ${kind}`;h.onpointerdown=e=>{e.preventDefault();e.stopPropagation();const rect=$('#stage').getBoundingClientRect(),cx=rect.left+rect.width*layer.x/100,cy=rect.top+rect.height*layer.y/100,startScale=layer.scale,startRotation=layer.rotation,startDistance=Math.hypot(e.clientX-cx,e.clientY-cy)||1,startAngle=Math.atan2(e.clientY-cy,e.clientX-cx);const move=p=>{if(kind==='scale')layer.scale=Math.max(5,Math.min(800,startScale*Math.hypot(p.clientX-cx,p.clientY-cy)/startDistance));else layer.rotation=startRotation+(Math.atan2(p.clientY-cy,p.clientX-cx)-startAngle)*180/Math.PI;updateSelected();syncProps()};const up=()=>{removeEventListener('pointermove',move);removeEventListener('pointerup',up);pushHistory();markDirty()};addEventListener('pointermove',move);addEventListener('pointerup',up)};el.append(h)}}
  const priorRenderLayers=renderLayers;renderLayers=function(){state.layers.forEach(ensureDefaults);priorRenderLayers();renderVectorPaths();addTransformHandles();renderMotionPath();renderMaskOverlay()};const priorSelectLayer=selectLayer;selectLayer=function(id){priorSelectLayer(id);$$('.transform-handle').forEach(e=>e.remove());addTransformHandles();syncProProps();renderTimeline();renderMaskOverlay()};

  $('#detachAudio').onclick=()=>{const video=selected();if(!video||video.type!=='video')return toast('Selecione uma camada de vídeo');const audio=addLayer('audio',video.content,`${video.name} · áudio`);Object.assign(audio,{sourcePath:video.sourcePath,mediaDuration:video.mediaDuration,sourceIn:video.sourceIn,sourceOut:video.sourceOut,start:video.start,end:video.end,speed:video.speed,volume:video.volume,pan:video.pan,audioChannel:video.audioChannel,waveform:[...(video.waveform||[])]});video.muted=true;renderLayers();selectLayer(audio.id);switchPanel('audio');pushHistory();toast('Áudio separado em uma nova camada')};

  function renderEffectStack(){const box=$('#effectStack');if(!box)return;const l=selected();if(!l){box.innerHTML='';return}ensureDefaults(l);const fx=l.effects||{},labels={rgb:'Canais RGB',brightness:'Brilho',contrast:'Contraste',saturation:'Saturação',hue:'Matiz',blur:'Desfoque',grayscale:'P&B',sepia:'Sépia',invert:'Inverter',glow:'Glow',vignette:'Vinheta',sharpen:'Nitidez',chromaTolerance:'Chroma key',motionBlur:'Motion blur'},defaults={brightness:100,contrast:100,saturation:100,redGain:100,greenGain:100,blueGain:100},isActive=k=>k==='rgb'?['redGain','greenGain','blueGain'].some(x=>(fx[x]??100)!==100):(fx[k]??defaults[k]??0)!==(defaults[k]??0),active=l.effectOrder.filter(k=>labels[k]&&isActive(k));for(const key of Object.keys(labels))if(!l.effectOrder.includes(key)&&isActive(key))active.push(key);box.innerHTML=active.map((k,i)=>`<div class="effect-chip"><span>${labels[k]}${k==='rgb'?` ${fx.redGain}/${fx.greenGain}/${fx.blueGain}`:`: ${fx[k]}`}</span><span><button data-up="${k}" ${i===0?'disabled':''}>↑</button><button data-down="${k}" ${i===active.length-1?'disabled':''}>↓</button><button data-remove-fx="${k}">×</button></span></div>`).join('')||'<div class="empty">Nenhum ajuste ativo</div>';const move=(key,delta)=>{const i=l.effectOrder.indexOf(key),j=Math.max(0,Math.min(l.effectOrder.length-1,i+delta));if(i<0||i===j)return;[l.effectOrder[i],l.effectOrder[j]]=[l.effectOrder[j],l.effectOrder[i]];l.filter=buildFilter(l);updateSelected();renderEffectStack();markDirty()};box.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>move(b.dataset.up,-1));box.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>move(b.dataset.down,1));box.querySelectorAll('[data-remove-fx]').forEach(b=>b.onclick=()=>{const key=b.dataset.removeFx;if(key==='rgb')for(const x of ['redGain','greenGain','blueGain'])l.effects[x]=100;else l.effects[key]=defaults[key]??0;l.filter=buildFilter(l);updateSelected();syncProps();markDirty()})}
  const proEffectFields={Glow:'glow',Vignette:'vignette',Sharpen:'sharpen',ChromaTolerance:'chromaTolerance',MotionBlur:'motionBlur',RedGain:'redGain',GreenGain:'greenGain',BlueGain:'blueGain'};for(const [id,key] of Object.entries(proEffectFields))$('#fx'+id)?.addEventListener('input',e=>{const l=selected();if(!l)return toast('Selecione uma camada');l.effects[key]=+e.target.value;$('#out'+id).value=e.target.value+(key==='motionBlur'?'px':'%');l.filter=buildFilter(l);updateSelected();renderEffectStack();markDirty()});
  $('#fxGlowColor').oninput=e=>{const l=selected();if(!l)return;l.glowColor=e.target.value;l.filter=buildFilter(l);updateSelected();markDirty()};$('#fxChromaColor').oninput=e=>{const l=selected();if(!l)return;l.chromaColor=e.target.value;markDirty()};

  let pendingExportFormat='mp4';const formatNames={mp4:'MP4 · H.264 + AAC',mov:'MOV · H.264 + AAC',webm:'WebM',gif:'GIF animado',png:'Imagem PNG',mp3:'Somente áudio MP3'};
  function applyExportPreset(value){const aspect=(state.composition?.width||1920)/(state.composition?.height||1080);if(value==='source'){$('#exportWidth').value=state.composition.width;$('#exportHeight').value=state.composition.height;return}const short=+value,w=aspect>=1?Math.round(short*aspect/2)*2:short,h=aspect>=1?short:Math.round(short/aspect/2)*2;$('#exportWidth').value=w;$('#exportHeight').value=h}
  $('#exportBtn').onclick=()=>$('#exportMenu').hidden=!$('#exportMenu').hidden;$$('[data-export-format]').forEach(button=>button.onclick=()=>{pendingExportFormat=button.dataset.exportFormat;$('#exportMenu').hidden=true;$('#exportFormatLabel').value=formatNames[pendingExportFormat];$('#exportFps').value=state.composition.fps;$('#exportStart').value=0;$('#exportEnd').value=state.duration;applyExportPreset($('#exportPreset').value);$('#exportTransparent').disabled=!['webm','png'].includes(pendingExportFormat);if($('#exportTransparent').disabled)$('#exportTransparent').checked=false;$('#exportSettings').hidden=false});$('#exportPreset').onchange=e=>applyExportPreset(e.target.value);$('#closeExportSettings').onclick=()=>$('#exportSettings').hidden=true;$('#startConfiguredExport').onclick=async()=>{const settings={width:+$('#exportWidth').value,height:+$('#exportHeight').value,fps:+$('#exportFps').value,quality:+$('#exportQuality').value,audioBitrate:$('#exportAudioBitrate').value,start:+$('#exportStart').value,end:+$('#exportEnd').value,transparent:$('#exportTransparent').checked};if(settings.end<=settings.start)return toast('O fim da exportação deve ser maior que o início');$('#exportSettings').hidden=true;await window.motionNativeExport(pendingExportFormat,settings)};

  renderLayers();renderTimeline();drawEasing();
})();
