/* Ferramentas profissionais: timeline editável, curvas, waveform, parenting e efeitos. */
(function(){
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const mediaTypes=new Set(['video','audio']);
  function ensureDefaults(l){if(l.mask&&!l.maskMode)l.maskMode='inset';return MotionProject.applyLayerDefaults(l,state.duration)}
  state.layers.forEach(ensureDefaults);
  const priorAddLayer=addLayer;
  addLayer=function(type,content,name){return ensureDefaults(priorAddLayer(type,content,name))};

  const easeValue=MotionAnimation.easeValue;
  interpolate=function(source,time){return MotionAnimation.evaluateLayer(source,time,{layers:state.layers,duration:state.duration})};

  function colorFilter(l){const id=`ml-color-${l.id}`,fx=l.effects||{},values=`${(fx.redGain??100)/100} 0 0 0 0 0 ${(fx.greenGain??100)/100} 0 0 0 0 0 ${(fx.blueGain??100)/100} 0 0 0 0 1 0`;let defs=$('#motionColorFilters');if(!defs){defs=document.createElementNS('http://www.w3.org/2000/svg','svg');defs.id='motionColorFilters';defs.style.display='none';document.body.append(defs)}let filter=defs.querySelector(`#${id}`);if(!filter){filter=document.createElementNS(defs.namespaceURI,'filter');filter.id=id;const matrix=document.createElementNS(defs.namespaceURI,'feColorMatrix');matrix.setAttribute('type','matrix');filter.append(matrix);defs.append(filter)}filter.firstElementChild.setAttribute('values',values);return `url(#${id})`}
  buildFilter=function(l){const fx=l.effects||{},rgb=(fx.redGain??100)!==100||(fx.greenGain??100)!==100||(fx.blueGain??100)!==100,filters={rgb:rgb?colorFilter(l):'',brightness:`brightness(${(fx.brightness??100)/100})`,contrast:`contrast(${(fx.contrast??100)/100})`,saturation:`saturate(${(fx.saturation??100)/100})`,hue:`hue-rotate(${fx.hue||0}deg)`,blur:`blur(${fx.blur||0}px)`,grayscale:`grayscale(${(fx.grayscale||0)/100})`,sepia:`sepia(${(fx.sepia||0)/100})`,invert:`invert(${(fx.invert||0)/100})`,sharpen:fx.sharpen?`contrast(${1+fx.sharpen/250})`:'',motionBlur:fx.motionBlur?`blur(${fx.motionBlur/3}px)`:'',glow:fx.glow?`drop-shadow(0 0 ${Math.max(1,fx.glow/3)}px ${l.glowColor||'#ffffff'})`:''};return (l.effectOrder||[]).map(key=>filters[key]).filter(Boolean).join(' ')||'none'};
  const inheritedApplyStyle=applyStyle;
  applyStyle=function(e,l){inheritedApplyStyle(e,{...l,filter:buildFilter(l)});e.classList.toggle('null-layer',l.type==='null');e.classList.toggle('camera-layer',l.type==='camera');e.classList.toggle('vignette',(l.effects?.vignette||0)>0);e.style.setProperty('--vignette',String((l.effects?.vignette||0)/100));if(l.fillType==='linear')e.style.background=`linear-gradient(${l.gradientAngle||0}deg,${l.color},${l.gradientColor})`;else if(l.fillType==='radial')e.style.background=`radial-gradient(circle,${l.color},${l.gradientColor})`;if(l.maskMode==='circle')e.style.clipPath='circle(48%)';else if(l.maskMode==='ellipse')e.style.clipPath='ellipse(48% 42%)';else if(l.maskMode==='polygon'&&(l.maskPoints||[]).length>2)e.style.clipPath=`polygon(${l.maskPoints.map(p=>`${p[0]}% ${p[1]}%`).join(',')})`;else if(l.maskMode==='inset')e.style.clipPath=`inset(${l.cropY||0}% ${l.cropX||0}% round ${l.radius||0}px)`;else e.style.clipPath=`inset(${l.cropY||0}% ${l.cropX||0}%)`};

  async function waveformFromFile(file){try{if(file.size>250*1024*1024)return[];const context=new AudioContext(),buffer=await context.decodeAudioData(await file.arrayBuffer()),data=buffer.getChannelData(0),count=180,step=Math.max(1,Math.floor(data.length/count)),points=[];for(let i=0;i<count;i++){let peak=0;for(let j=0;j<step;j++)peak=Math.max(peak,Math.abs(data[i*step+j]||0));points.push(Math.round(peak*1000)/1000)}await context.close();return points}catch{return []}}
  const priorImportMedia=importMedia;
  importMedia=async function(file){const before=new Set(state.layers.map(l=>l.id));await priorImportMedia(file);const layer=state.layers.find(l=>!before.has(l.id));if(layer&&file.type.startsWith('video')){MotionProjectCommands.setLayerWaveform(state,{id:layer.id,points:await waveformFromFile(file)});renderTimeline();pushHistory()}return layer};
  $('#audioInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;const url=URL.createObjectURL(file),probe=document.createElement('audio');const duration=await new Promise(resolve=>{probe.onloadedmetadata=()=>resolve(Number.isFinite(probe.duration)?probe.duration:state.duration);probe.onerror=()=>resolve(state.duration);probe.src=url}),waveform=await waveformFromFile(file),layer=addMediaDescriptor({type:'audio',url,name:file.name,sourcePath:window.motionDesktop?.getPathForFile?.(file)||'',duration,waveform,hasAudio:true});MotionProjectCommands.setLayerWaveform(state,{id:layer.id,points:waveform,hasAudio:true});renderLayers();selectLayer(layer.id);switchPanel('audio');pushHistory();markDirty();e.target.value=''};

  $('#timelineZoom').oninput=e=>{MotionUiState.timelineZoom=+e.target.value;renderTimeline();setTime(state.playback.time)};$('#snapTimeline').onchange=e=>MotionUiState.snapTimeline=e.target.checked;$('#addMarker').onclick=()=>{MotionProjectCommands.addMarker(state,{time:state.playback.time});renderTimeline();markDirty()};$('#clearMarkers').onclick=()=>{MotionProjectCommands.setMarkers(state,{kind:'manual',markers:[]});renderTimeline();markDirty()};
  const newProjectAction=$('#newProject').onclick;$('#newProject').onclick=e=>{finishVectorEdit(true);newProjectAction.call($('#newProject'),e);renderTimeline()};

  function drawEasing(){const c=$('#easingGraph'),g=c.getContext('2d'),type=selected()?.easing||'linear';g.clearRect(0,0,c.width,c.height);g.strokeStyle='#303642';for(let i=1;i<5;i++){g.beginPath();g.moveTo(i*c.width/5,0);g.lineTo(i*c.width/5,c.height);g.stroke()}g.strokeStyle='#9d7cff';g.lineWidth=3;g.beginPath();for(let i=0;i<=100;i++){const p=i/100,x=10+p*(c.width-20),y=c.height-10-easeValue(p,type)*(c.height-20);i?g.lineTo(x,y):g.moveTo(x,y)}g.stroke()}
  function syncProProps(){const l=selected();if(!l)return;ensureDefaults(l);$('#propDepth').value=l.depth;$('#outDepth').value=l.depth;$('#propPerspective').value=l.perspective;$('#outPerspective').value=l.perspective;$('#propEasing').value=l.easing;$('#propTransitionIn').value=l.transitionIn;$('#propTransitionOut').value=l.transitionOut;$('#propTransitionDuration').value=l.transitionDuration;$('#propReverse').checked=l.reverse;$('#propFillType').value=l.fillType;$('#propGradientColor').value=l.gradientColor;$('#propGradientAngle').value=l.gradientAngle;$('#outGradientAngle').value=l.gradientAngle+'°';$('#propMaskMode').value=l.maskMode;$('#fxGlowColor').value=l.glowColor||'#ffffff';$('#fxChromaColor').value=l.chromaColor||'#00ff00';for(const [id,key] of Object.entries(proEffectFields)){const value=l.effects?.[key]??(key.endsWith('Gain')?100:0);$('#fx'+id).value=value;$('#out'+id).value=value+(key==='motionBlur'?'px':'%')}const parent=$('#propParent'),current=String(l.parentId||'');parent.innerHTML='<option value="">Nenhuma</option>'+state.layers.filter(x=>x.id!==l.id).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');parent.value=current;drawEasing();renderEffectStack();renderMotionPath()}
  const priorSyncProps=syncProps;syncProps=function(){priorSyncProps();syncProProps()};
  for(const [id,key,type] of [['propDepth','depth','number'],['propPerspective','perspective','number'],['propEasing','easing','value'],['propTransitionIn','transitionIn','value'],['propTransitionOut','transitionOut','value'],['propTransitionDuration','transitionDuration','number'],['propReverse','reverse','checked'],['propFillType','fillType','value'],['propGradientColor','gradientColor','value'],['propGradientAngle','gradientAngle','number'],['propMaskMode','maskMode','value'],['propParent','parentId','parent']])$('#'+id).oninput=e=>{const l=selected();if(!l)return;try{if(!MotionProjectCommands.setProperties(state,{id:l.id,values:{[key]:type==='checked'?e.target.checked:type==='number'?+e.target.value:type==='parent'?(+e.target.value||null):e.target.value}}))return}catch(error){syncProProps();return toast(error.message)}updateSelected();syncProProps();renderLayers();selectLayer(l.id);markDirty()};
  $('#addKeyframe').onclick=()=>{const l=selected();if(!l)return;const property=$('#keyframeProperty').value,values={};for(const key of property==='all'?['x','y','depth','scale','rotation','opacity']:[property])values[key]=l[key];if(!MotionProjectCommands.setKeyframe(state,{id:l.id,time:state.playback.time,values,easing:l.easing}))return;renderTimeline();renderMotionPath();pushHistory();markDirty();toast(`Keyframe de ${property==='all'?'transformação':property} criado`)};
  $('#addNullLayer').onclick=()=>{pushHistory();const l=MotionProjectCommands.createControlLayer(state,{id:uid++,kind:'null',name:`Controle nulo ${state.layers.filter(x=>x.type==='null').length+1}`});if(!l)return;renderLayers();selectLayer(l.id);markDirty()};$('#addCameraLayer').onclick=()=>{pushHistory();const l=MotionProjectCommands.createControlLayer(state,{id:uid++,kind:'camera',name:`Câmera ${state.layers.filter(x=>x.type==='camera').length+1}`});if(!l)return toast('Desbloqueie a câmera ativa antes de substituí-la');renderLayers();selectLayer(l.id);markDirty()};$('#showMotionPath').onclick=()=>{MotionUiState.showMotionPath=!MotionUiState.showMotionPath;renderMotionPath();$('#showMotionPath').textContent=MotionUiState.showMotionPath?'Ocultar caminho de movimento':'Exibir caminho de movimento'};
  $('#precomposeLayers').onclick=()=>{const children=state.layers.filter(l=>state.selection.selectedIds.has(l.id));if(children.length<2)return toast('Marque pelo menos duas camadas na timeline');const controller=addLayer('null','',`Precomposição ${Date.now().toString().slice(-4)}`);if(!MotionProjectCommands.precompose(state,{controllerId:controller.id,childIds:children.map(l=>l.id)})){MotionLayerCommands.remove(state,controller.id);return toast('Não foi possível precompor camadas bloqueadas')}renderLayers();selectLayer(controller.id);pushHistory();toast(`${children.length} camadas precompostas`)};

  function renderMotionPath(){document.querySelector('.motion-path')?.remove();const l=selected();if(!l||!MotionUiState.showMotionPath)return;const points=(l.keyframes||[]).filter(k=>Number.isFinite(k.values?.x)&&Number.isFinite(k.values?.y)).sort((a,b)=>a.time-b.time);if(points.length<2)return;const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('motion-path');svg.setAttribute('viewBox','0 0 100 100');const poly=document.createElementNS(svg.namespaceURI,'polyline');poly.setAttribute('points',points.map(p=>`${p.values.x},${p.values.y}`).join(' '));svg.append(poly);for(const p of points){const dot=document.createElementNS(svg.namespaceURI,'circle');dot.setAttribute('cx',p.values.x);dot.setAttribute('cy',p.values.y);dot.setAttribute('r','1.4');svg.append(dot)}$('#stage').append(svg)}
  function renderMaskOverlay(){document.querySelector('.mask-path')?.remove();const l=selected(),el=l&&$(`.layer[data-id="${l.id}"]`);if(!l||!el||l.maskMode!=='polygon'||l.maskPoints.length<1)return;const stage=$('#stage').getBoundingClientRect(),rect=el.getBoundingClientRect(),svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('mask-path');svg.setAttribute('viewBox','0 0 100 100');const mapped=l.maskPoints.map(p=>[(rect.left-stage.left+rect.width*p[0]/100)/stage.width*100,(rect.top-stage.top+rect.height*p[1]/100)/stage.height*100]);const poly=document.createElementNS(svg.namespaceURI,'polygon');poly.setAttribute('points',mapped.map(p=>p.join(',')).join(' '));svg.append(poly);for(const p of mapped){const dot=document.createElementNS(svg.namespaceURI,'circle');dot.setAttribute('cx',p[0]);dot.setAttribute('cy',p[1]);dot.setAttribute('r','1.2');svg.append(dot)}$('#stage').append(svg)}
  let vectorEdit=null;
  function syncVectorEditUi(){MotionUiState.maskEditing=vectorEdit?.kind==='mask';MotionUiState.pathEditing=vectorEdit?.kind==='path';$('#editMaskPoints').textContent=MotionUiState.maskEditing?'Clique no elemento · duplo clique encerra':'Editar máscara no palco';$('#startBezierPath').textContent=MotionUiState.pathEditing?'Clique no palco · duplo clique encerra':'Caneta Bézier'}
  function finishVectorEdit(commit){if(!vectorEdit)return false;const raw=commit?null:projectHistory.cancel();if(commit)projectHistory.commit(snapshot());vectorEdit=null;syncVectorEditUi();if(raw!==null)restore(raw);return true}
  function beginVectorEdit(kind,id){if(vectorEdit)finishVectorEdit(true);projectHistory.begin(snapshot());vectorEdit={kind,id};syncVectorEditUi()}
  document.addEventListener('motion:beforehistorygesture',()=>finishVectorEdit(true));
  $('#editMaskPoints').onclick=()=>{const l=selected();if(!l)return toast('Selecione uma camada');if(vectorEdit?.kind==='mask'&&vectorEdit.id===l.id){finishVectorEdit(true);return}if(l.locked)return toast('Desbloqueie a camada para editar a máscara');beginVectorEdit('mask',l.id);MotionProjectCommands.setProperties(state,{id:l.id,values:{maskMode:'polygon'}});renderLayers();selectLayer(l.id)};$('#clearMaskPoints').onclick=()=>{const l=selected();if(!l)return;if(vectorEdit)finishVectorEdit(true);MotionProjectCommands.setVectorPoints(state,{id:l.id,kind:'mask',points:[]});MotionProjectCommands.setProperties(state,{id:l.id,values:{maskMode:'none'}});renderLayers();selectLayer(l.id);markDirty()};$('#stage').addEventListener('pointerdown',e=>{if(vectorEdit?.kind!=='mask')return;const l=state.layers.find(item=>item.id===vectorEdit.id),el=l&&$(`.layer[data-id="${l.id}"]`);if(!el)return;e.preventDefault();e.stopPropagation();const r=el.getBoundingClientRect();MotionProjectCommands.appendVectorPoint(state,{id:l.id,kind:'mask',point:[Math.max(0,Math.min(100,(e.clientX-r.left)/r.width*100)),Math.max(0,Math.min(100,(e.clientY-r.top)/r.height*100))]});applyStyle(el,l);renderMaskOverlay();markDirty()},true);$('#stage').addEventListener('dblclick',e=>{if(vectorEdit?.kind!=='mask')return;e.preventDefault();finishVectorEdit(true);toast('Máscara personalizada concluída')},true);

  function bezierPath(points){if(!points?.length)return'';if(points.length===1)return`M ${points[0][0]} ${points[0][1]}`;let d=`M ${points[0][0]} ${points[0][1]}`;for(let i=1;i<points.length-1;i++){const mid=[(points[i][0]+points[i+1][0])/2,(points[i][1]+points[i+1][1])/2];d+=` Q ${points[i][0]} ${points[i][1]} ${mid[0]} ${mid[1]}`}const last=points.at(-1);return d+` T ${last[0]} ${last[1]}`}
  function renderVectorPaths(){for(const l of state.layers.filter(x=>x.type==='path')){const e=$(`.layer[data-id="${l.id}"]`);if(!e)continue;e.classList.add('path-layer');e.innerHTML=`<svg viewBox="0 0 100 100" preserveAspectRatio="none"><path d="${bezierPath(l.pathPoints||[])}" fill="none" stroke="${l.color||'#fff'}" stroke-width="${Math.max(.3,l.stroke||1)}" stroke-linecap="round" stroke-linejoin="round"/></svg>`;applyStyle(e,l)}}
  $('#startBezierPath').onclick=()=>{let l=selected();if(vectorEdit?.kind==='path'&&l?.id===vectorEdit.id){finishVectorEdit(true);return}if(vectorEdit)finishVectorEdit(true);projectHistory.begin(snapshot());if(!l||l.type!=='path'){l=addLayer('path','',`Caminho Bézier ${state.layers.filter(x=>x.type==='path').length+1}`);MotionProjectCommands.setVectorPoints(state,{id:l.id,kind:'path',points:[]});MotionProjectCommands.setProperties(state,{id:l.id,values:{x:50,y:50,scale:100,stroke:2}})}else if(l.locked){projectHistory.cancel();return toast('Desbloqueie a camada para editar o caminho')}vectorEdit={kind:'path',id:l.id};syncVectorEditUi();renderLayers();selectLayer(l.id)};$('#stage').addEventListener('pointerdown',e=>{if(vectorEdit?.kind!=='path')return;const l=state.layers.find(item=>item.id===vectorEdit.id);if(!l)return;e.preventDefault();e.stopPropagation();const r=$('#stage').getBoundingClientRect();MotionProjectCommands.appendVectorPoint(state,{id:l.id,kind:'path',point:[(e.clientX-r.left)/r.width*100,(e.clientY-r.top)/r.height*100]});renderVectorPaths();markDirty()},true);$('#stage').addEventListener('dblclick',e=>{if(vectorEdit?.kind!=='path')return;e.preventDefault();finishVectorEdit(true);toast('Caminho Bézier concluído')},true);
  addEventListener('keydown',e=>{if(e.key!=='Escape'||!vectorEdit)return;e.preventDefault();finishVectorEdit(false);toast('Edição vetorial cancelada')});
  function addTransformHandles(){const layer=selected(),el=layer&&$(`.layer[data-id="${layer.id}"]`);if(!el||layer.locked||layer.type==='audio')return;for(const kind of ['scale','rotate']){const h=document.createElement('i');h.className=`transform-handle ${kind}`;h.onpointerdown=e=>{e.preventDefault();e.stopPropagation();const rect=$('#stage').getBoundingClientRect(),cx=rect.left+rect.width*layer.x/100,cy=rect.top+rect.height*layer.y/100,startScale=layer.scale,startRotation=layer.rotation,startDistance=Math.hypot(e.clientX-cx,e.clientY-cy)||1,startAngle=Math.atan2(e.clientY-cy,e.clientX-cx);projectHistory.begin(snapshot());const move=p=>{const values=kind==='scale'?{scale:Math.max(5,Math.min(800,startScale*Math.hypot(p.clientX-cx,p.clientY-cy)/startDistance))}:{rotation:startRotation+(Math.atan2(p.clientY-cy,p.clientX-cx)-startAngle)*180/Math.PI};MotionProjectCommands.setProperties(state,{id:layer.id,values});updateSelected();syncProps()};const up=p=>{removeEventListener('pointermove',move);removeEventListener('pointerup',up);removeEventListener('pointercancel',up);if(p.type==='pointercancel'){MotionProjectCommands.setProperties(state,{id:layer.id,values:{scale:startScale,rotation:startRotation}});projectHistory.cancel();updateSelected();syncProps()}else projectHistory.commit(snapshot());markDirty()};addEventListener('pointermove',move);addEventListener('pointerup',up);addEventListener('pointercancel',up)};el.append(h)}}
  const priorRenderLayers=renderLayers;renderLayers=function(){priorRenderLayers();renderVectorPaths();addTransformHandles();renderMotionPath();renderMaskOverlay()};const priorSelectLayer=selectLayer;selectLayer=function(id){priorSelectLayer(id);$$('.transform-handle').forEach(e=>e.remove());addTransformHandles();syncProProps();renderTimeline();renderMaskOverlay()};

  function detachAudio(video=selected()){if(!video||video.type!=='video')return toast('Selecione uma camada de vídeo');if(!video.hasAudio&&!video.waveform?.length)return toast('Este vídeo não possui áudio detectado');pushHistory();const audio=MotionLayerCommands.detachAudio(state,{videoId:video.id,nextId:uid++,trackId:`track-${crypto.randomUUID()}`});if(!audio)return toast('Este vídeo não possui áudio detectado');renderLayers();selectLayer(audio.id);switchPanel('audio');pushHistory();markDirty();toast('Áudio extraído para uma faixa independente');return audio}
  window.motionDetachAudio=detachAudio;$('#detachAudio').onclick=()=>detachAudio();

  function renderEffectStack(){const box=$('#effectStack');if(!box)return;const l=selected();if(!l){box.innerHTML='';return}ensureDefaults(l);const fx=l.effects||{},labels={rgb:'Canais RGB',brightness:'Brilho',contrast:'Contraste',saturation:'Saturação',hue:'Matiz',blur:'Desfoque',grayscale:'P&B',sepia:'Sépia',invert:'Inverter',glow:'Glow',vignette:'Vinheta',sharpen:'Nitidez',chromaTolerance:'Chroma key',motionBlur:'Motion blur'},defaults={brightness:100,contrast:100,saturation:100,redGain:100,greenGain:100,blueGain:100},isActive=k=>k==='rgb'?['redGain','greenGain','blueGain'].some(x=>(fx[x]??100)!==100):(fx[k]??defaults[k]??0)!==(defaults[k]??0),active=l.effectOrder.filter(k=>labels[k]&&isActive(k));for(const key of Object.keys(labels))if(!l.effectOrder.includes(key)&&isActive(key))active.push(key);box.innerHTML=active.map((k,i)=>`<div class="effect-chip"><span>${labels[k]}${k==='rgb'?` ${fx.redGain}/${fx.greenGain}/${fx.blueGain}`:`: ${fx[k]}`}</span><span><button data-up="${k}" ${i===0?'disabled':''}>↑</button><button data-down="${k}" ${i===active.length-1?'disabled':''}>↓</button><button data-remove-fx="${k}">×</button></span></div>`).join('')||'<div class="empty">Nenhum ajuste ativo</div>';const refresh=()=>{MotionProjectCommands.setProperties(state,{id:l.id,values:{filter:buildFilter(l)}});updateSelected();renderEffectStack();markDirty()},move=(key,delta)=>{if(MotionProjectCommands.moveEffect(state,{id:l.id,key,direction:delta}))refresh()};box.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>move(b.dataset.up,-1));box.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>move(b.dataset.down,1));box.querySelectorAll('[data-remove-fx]').forEach(b=>b.onclick=()=>{if(MotionProjectCommands.resetEffect(state,{id:l.id,key:b.dataset.removeFx})){refresh();syncProps()}})}
  const proEffectFields={Glow:'glow',Vignette:'vignette',Sharpen:'sharpen',ChromaTolerance:'chromaTolerance',MotionBlur:'motionBlur',RedGain:'redGain',GreenGain:'greenGain',BlueGain:'blueGain'};for(const [id,key] of Object.entries(proEffectFields))$('#fx'+id)?.addEventListener('input',e=>{const l=selected();if(!l)return toast('Selecione uma camada');MotionProjectCommands.setEffects(state,{id:l.id,values:{[key]:+e.target.value}});$('#out'+id).value=e.target.value+(key==='motionBlur'?'px':'%');MotionProjectCommands.setProperties(state,{id:l.id,values:{filter:buildFilter(l)}});updateSelected();renderEffectStack();markDirty()});
  $('#fxGlowColor').oninput=e=>{const l=selected();if(!l)return;MotionProjectCommands.setProperties(state,{id:l.id,values:{glowColor:e.target.value}});MotionProjectCommands.setProperties(state,{id:l.id,values:{filter:buildFilter(l)}});updateSelected();markDirty()};$('#fxChromaColor').oninput=e=>{const l=selected();if(!l)return;MotionProjectCommands.setProperties(state,{id:l.id,values:{chromaColor:e.target.value}});markDirty()};
  ['propDepth','propPerspective','propEasing','propTransitionIn','propTransitionOut','propTransitionDuration','propReverse','propFillType','propGradientColor','propGradientAngle','propMaskMode','propParent','fxGlowColor','fxChromaColor',...Object.keys(proEffectFields).map(id=>'fx'+id)].forEach(id=>bindHistoryGesture($('#'+id)));

  let pendingExportFormat='mp4';const formatNames={mp4:'MP4 · H.264 + AAC',mov:'MOV · H.264 + AAC',webm:'WebM',gif:'GIF animado',png:'Imagem PNG',mp3:'Somente áudio MP3'};
  function applyExportPreset(value){const aspect=(state.composition?.width||1920)/(state.composition?.height||1080);if(value==='source'){$('#exportWidth').value=state.composition.width;$('#exportHeight').value=state.composition.height;return}const short=+value,w=aspect>=1?Math.round(short*aspect/2)*2:short,h=aspect>=1?short:Math.round(short/aspect/2)*2;$('#exportWidth').value=w;$('#exportHeight').value=h}
  $('#exportBtn').onclick=()=>$('#exportMenu').hidden=!$('#exportMenu').hidden;$$('[data-export-format]').forEach(button=>button.onclick=()=>{pendingExportFormat=button.dataset.exportFormat;$('#exportMenu').hidden=true;$('#exportFormatLabel').value=formatNames[pendingExportFormat];$('#exportFps').value=state.composition.fps;$('#exportStart').value=state.renderRange?.start||0;$('#exportEnd').value=state.renderRange?.end??state.duration;applyExportPreset($('#exportPreset').value);$('#exportTransparent').disabled=!['webm','png'].includes(pendingExportFormat);if($('#exportTransparent').disabled)$('#exportTransparent').checked=false;$('#exportSettings').hidden=false});$('#exportPreset').onchange=e=>applyExportPreset(e.target.value);$('#closeExportSettings').onclick=()=>$('#exportSettings').hidden=true;$('#startConfiguredExport').onclick=async()=>{const settings={width:+$('#exportWidth').value,height:+$('#exportHeight').value,fps:+$('#exportFps').value,quality:+$('#exportQuality').value,audioBitrate:$('#exportAudioBitrate').value,start:+$('#exportStart').value,end:+$('#exportEnd').value,transparent:$('#exportTransparent').checked};try{if(!MotionProjectCommands.setRenderRange(state,{start:settings.start,end:settings.end}))return toast('O fim da exportação deve ser maior que o início')}catch(error){return toast(error.message)}$('#exportSettings').hidden=true;await window.motionNativeExport(pendingExportFormat,settings).catch(()=>{})};

  renderLayers();renderTimeline();drawEasing();
})();
