(function(root){
function create({document,media:mediaSource,viewport}){
function calculateMediaFit(sw,sh,fw,fh,mode='contain'){sw=Math.max(1,sw);sh=Math.max(1,sh);if(mode==='fill')return{width:fw,height:fh};const scale=(mode==='cover'?Math.max:Math.min)(fw/sw,fh/sh);return{width:sw*scale,height:sh*scale}}
  function canvasFill(ctx,l,w,h){if(l.fillType==='linear'){const a=(l.gradientAngle||0)*Math.PI/180,x=Math.cos(a)*w/2,y=Math.sin(a)*h/2,g=ctx.createLinearGradient(-x,-y,x,y);g.addColorStop(0,l.color||'#fff');g.addColorStop(1,l.gradientColor||'#7758ff');return g}if(l.fillType==='radial'){const g=ctx.createRadialGradient(0,0,0,0,0,Math.max(w,h)/2);g.addColorStop(0,l.color||'#fff');g.addColorStop(1,l.gradientColor||'#7758ff');return g}return l.color||'#fff'}
  function clipLayer(ctx,l,w,h){const x=(50-(l.anchorX??50))/100*w,y=(50-(l.anchorY??50))/100*h;ctx.beginPath();if(l.maskMode==='circle')ctx.arc(x,y,Math.min(w,h)*.48,0,Math.PI*2);else if(l.maskMode==='ellipse')ctx.ellipse(x,y,w*.48,h*.42,0,0,Math.PI*2);else if(l.maskMode==='polygon'&&l.maskPoints?.length>2){l.maskPoints.forEach((p,i)=>{const px=x-w/2+p[0]/100*w,py=y-h/2+p[1]/100*h;i?ctx.lineTo(px,py):ctx.moveTo(px,py)});ctx.closePath()}else{const cx=(l.cropX||0)/100*w,cy=(l.cropY||0)/100*h;ctx.rect(x-w/2+cx,y-h/2+cy,w-cx*2,h-cy*2)}ctx.clip()}
  function chromaCanvas(media,l){const fx=l.effects||{},tolerance=fx.chromaTolerance||0,gains=[(fx.redGain??100)/100,(fx.greenGain??100)/100,(fx.blueGain??100)/100],sharpen=(fx.sharpen||0)/100,processing=tolerance||sharpen||gains.some(x=>x!==1);if(!processing)return media;const sw=media.videoWidth||media.naturalWidth||media.width,sh=media.videoHeight||media.naturalHeight||media.height;if(!sw||!sh)return media;const scale=Math.min(1,1280/sw),c=document.createElement('canvas');c.width=Math.max(1,Math.round(sw*scale));c.height=Math.max(1,Math.round(sh*scale));const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(media,0,0,c.width,c.height);try{const image=g.getImageData(0,0,c.width,c.height),data=image.data,hex=l.chromaColor||'#00ff00',target=[parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5,7),16)],limit=tolerance*4.42;for(let i=0;i<data.length;i+=4){if(tolerance){const d=Math.hypot(data[i]-target[0],data[i+1]-target[1],data[i+2]-target[2]);if(d<limit)data[i+3]=Math.round(255*d/limit)}data[i]=Math.min(255,data[i]*gains[0]);data[i+1]=Math.min(255,data[i+1]*gains[1]);data[i+2]=Math.min(255,data[i+2]*gains[2])}if(sharpen){const original=new Uint8ClampedArray(data),w=c.width,h=c.height,a=sharpen*.7;for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=(y*w+x)*4;for(let channel=0;channel<3;channel++)data[i+channel]=Math.max(0,Math.min(255,original[i+channel]*(1+4*a)-a*(original[i-4+channel]+original[i+4+channel]+original[i-w*4+channel]+original[i+w*4+channel])))}}g.putImageData(image,0,0)}catch{}return c}
  function vignette(ctx,l,w,h,x,y){const amount=(l.effects?.vignette||0)/100;if(!amount)return;const g=ctx.createRadialGradient(x,y,Math.min(w,h)*.2,x,y,Math.max(w,h)*.72);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(1,`rgba(0,0,0,${amount})`);ctx.fillStyle=g;ctx.fillRect(x-w/2,y-h/2,w,h)}
  function draw(ctx,canvas,time,state,transparent=false,layerSources=state.layers){
    ctx.clearRect(0,0,canvas.width,canvas.height);if(!transparent){ctx.save();ctx.fillStyle=state.composition?.background||'#08090b';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.restore()}
    const stageRect=viewport(),sx=canvas.width/stageRect.width,sy=canvas.height/stageRect.height;
    for(const source of layerSources){
      if(source.visible===false||source.type==='audio'||time<(source.start||0)||time>(source.end??state.duration))continue;
      const l=MotionAnimation.evaluateLayer(source,time,{layers:state.layers,duration:state.duration});
      ctx.save();ctx.globalAlpha=(l.opacity??100)/100;ctx.globalCompositeOperation=l.blend==='normal'?'source-over':(l.blend||'source-over');ctx.filter=(l.filter||'none').replace(/url\([^)]*\)\s*/g,'')||'none';ctx.translate(l.x/100*canvas.width,l.y/100*canvas.height);ctx.rotate((l.rotation||0)*Math.PI/180);ctx.scale((l.flipX?-1:1)*(l.scale||100)/100,(l.flipY?-1:1)*(l.scale||100)/100);
      ctx.fillStyle=l.color||'#fff';ctx.strokeStyle=l.strokeColor||'#000';ctx.lineWidth=(l.stroke||0)*Math.max(sx,sy);
      if(l.type==='text'){ctx.font=`700 ${(l.fontSize||42)*sy}px ${l.font||'Segoe UI'}`;ctx.textAlign='center';ctx.textBaseline='middle';if(l.stroke)ctx.strokeText(l.content||'',0,0);ctx.fillText(l.content||'',0,0)}
      else if(l.type==='rect'){const w=160*sx,h=100*sy,r=Math.min(l.radius||0,50)/100*Math.min(w,h);ctx.fillStyle=canvasFill(ctx,l,w,h);clipLayer(ctx,l,w,h);ctx.beginPath();ctx.roundRect(-w/2,-h/2,w,h,r);ctx.fill();if(l.stroke)ctx.stroke()}
      else if(l.type==='circle'){const size=120*Math.min(sx,sy);ctx.fillStyle=canvasFill(ctx,l,size,size);ctx.beginPath();ctx.arc(0,0,size/2,0,Math.PI*2);ctx.fill();if(l.stroke)ctx.stroke()}
      else if(l.type==='path'&&l.pathPoints?.length){ctx.beginPath();const points=l.pathPoints.map(p=>[(p[0]-50)*canvas.width,(p[1]-50)*canvas.height]);ctx.moveTo(...points[0]);for(let i=1;i<points.length-1;i++){const mid=[(points[i][0]+points[i+1][0])/2,(points[i][1]+points[i+1][1])/2];ctx.quadraticCurveTo(points[i][0],points[i][1],mid[0],mid[1])}if(points.length>1)ctx.lineTo(...points.at(-1));ctx.strokeStyle=l.color||'#fff';ctx.lineWidth=Math.max(1,(l.stroke||2)*Math.max(sx,sy));ctx.lineCap='round';ctx.lineJoin='round';ctx.stroke()}
      else if(l.type!=='null'){const media=mediaSource.get(source);if(media&&media.readyState!==0){const sourceWidth=media.videoWidth||media.naturalWidth||l.mediaWidth||media.clientWidth,sourceHeight=media.videoHeight||media.naturalHeight||l.mediaHeight||media.clientHeight,fit=calculateMediaFit(sourceWidth,sourceHeight,canvas.width,canvas.height,l.fitMode||'contain'),w=fit.width,h=fit.height,x=(50-(l.anchorX??50))/100*w,y=(50-(l.anchorY??50))/100*h;try{clipLayer(ctx,l,w,h);ctx.drawImage(chromaCanvas(media,l),x-w/2,y-h/2,w,h);vignette(ctx,l,w,h,x,y)}catch{}}}
      ctx.restore();
    }
  }

return{draw};
}
root.MotionRasterizer={create};
})(globalThis);
