import type {History} from '../../core/history';
import {add} from '../../core/layer-commands';
import {createLayer,type Layer} from '../../core/project-model';
import {setAnimatedProperties,setProperties} from '../../core/project-commands';
import {selectOnly} from '../../core/selection-commands';
import type {EditorState} from '../../core/editor-state';
import type {MediaRuntime} from '../../renderer/media-runtime';
import {h,render} from 'vue';
import StageLayer from '../components/stage/StageLayer.vue';
import {getUiAppContext} from '../vue-app-context';

interface StageControllerContext {state:EditorState;mediaRuntime:MediaRuntime;nextId():number;history():History;snapshot():string;renderTimeline():void;markDirty():void;toast(message:string):void}
export interface StageController {addLayer(type:string,content:string,name:string):Layer;applyStyle(element:HTMLElement,layer:Layer):void;beginDrag(event:PointerEvent,layer:Layer):void;renderLayers():void;selectLayer(id:number|null):void;selected():Layer|null;syncProps():void;updateSelected():void}
type BasicKey='x'|'y'|'scaleX'|'scaleY'|'rotation'|'opacity'|'color';
const byId=<T extends HTMLElement>(id:string):T=>{const element=document.getElementById(id);if(!element)throw new Error(`Elemento ausente: ${id}`);return element as T};

export function installStageController(context:StageControllerContext):StageController {
  let renderLayers=()=>{},syncProps=()=>{},selectLayer=(_id:number|null)=>{},updateSelected=()=>{};
  const layerHosts=new Map<number,{mount:HTMLElement;element:HTMLElement;kind:string}>();
  const selected=()=>context.state.layers.find(layer=>layer.id===context.state.selection.selected)||null;
  const applyStyle=(element:HTMLElement,layer:Layer)=>{element.style.left=`${layer.x}%`;element.style.top=`${layer.y}%`;element.style.opacity=String(layer.opacity/100);element.style.color=layer.color;element.style.backgroundColor=layer.type==='rect'||layer.type==='circle'?layer.color:'';element.style.filter=layer.filter;element.style.setProperty('--media-fit',layer.fitMode||'contain');element.style.transformOrigin=`${layer.anchorX??50}% ${layer.anchorY??50}%`;element.style.clipPath=`inset(${layer.cropY||0}% ${layer.cropX||0}%)`;element.style.transform=`translate(-50%,-50%) scale(${(layer.flipX?-1:1)*(layer.scaleX??layer.scale)/100},${(layer.flipY?-1:1)*(layer.scaleY??layer.scale)/100}) rotate(${layer.rotation}deg)`;element.style.visibility=layer.visible===false?'hidden':'visible';element.classList.toggle('selected',layer.id===context.state.selection.selected)};
  const beginDrag=(event:PointerEvent,layer:Layer)=>{if(layer.locked)return context.toast('Camada bloqueada');if(event.button!==0||layer.id===undefined)return;selectLayer(layer.id);const bounds=byId<HTMLElement>('stage').getBoundingClientRect(),before={x:layer.x,y:layer.y},beforeKeyframes=structuredClone(layer.keyframes),origin={x:Number.isFinite(event.clientX)?event.clientX:bounds.left+bounds.width*before.x/100,y:Number.isFinite(event.clientY)?event.clientY:bounds.top+bounds.height*before.y/100},history=context.history();history.begin(context.snapshot());const move=(pointer:PointerEvent)=>{setAnimatedProperties(context.state,{id:layer.id!,time:context.state.playback.time,values:{x:Math.max(0,Math.min(100,before.x+(pointer.clientX-origin.x)/bounds.width*100)),y:Math.max(0,Math.min(100,before.y+(pointer.clientY-origin.y)/bounds.height*100))}});updateSelected();syncProps();context.markDirty()};const up=(pointer:PointerEvent)=>{removeEventListener('pointermove',move);removeEventListener('pointerup',up);removeEventListener('pointercancel',up);if(pointer.type==='pointercancel'){setProperties(context.state,{id:layer.id!,values:before});layer.keyframes=beforeKeyframes;history.cancel();updateSelected();syncProps()}else history.commit(context.snapshot());context.renderTimeline();context.markDirty()};addEventListener('pointermove',move);addEventListener('pointerup',up);addEventListener('pointercancel',up)};
  renderLayers=()=>{const stage=byId<HTMLElement>('stage'),activeIds=new Set<number>();const hint=document.querySelector<HTMLElement>('.stage-hint');if(hint)hint.hidden=context.state.layers.length>0;for(const layer of context.state.layers){if(layer.id===undefined)continue;activeIds.add(layer.id);let host=layerHosts.get(layer.id);if(host&&host.kind!==layer.type){render(null,host.mount);host.element.remove();layerHosts.delete(layer.id);host=undefined}if(!host){const mount=document.createElement('div'),vnode=h(StageLayer,{id:layer.id,kind:layer.type,content:layer.content,selected:layer.id===context.state.selection.selected,onDrag:(event:PointerEvent)=>beginDrag(event,layer),onSelect:(event:MouseEvent)=>{event.stopPropagation();selectLayer(layer.id!)}});vnode.appContext=getUiAppContext();render(vnode,mount);const element=mount.firstElementChild as HTMLElement;host={mount,element,kind:layer.type};layerHosts.set(layer.id,host)}else{const vnode=h(StageLayer,{id:layer.id,kind:layer.type,content:layer.content,selected:layer.id===context.state.selection.selected,onDrag:(event:PointerEvent)=>beginDrag(event,layer),onSelect:(event:MouseEvent)=>{event.stopPropagation();selectLayer(layer.id!)}});vnode.appContext=getUiAppContext();render(vnode,host.mount)}const element=host.element;if(['image','video','audio','drawing'].includes(layer.type)){context.mediaRuntime.attach(layer,element);if(layer.type==='audio')element.style.display='none'}applyStyle(element,layer);if(element.parentElement!==stage)stage.append(element)}context.mediaRuntime.reconcile(context.state.layers);for(const [id,host] of layerHosts)if(!activeIds.has(id)){render(null,host.mount);host.element.remove();layerHosts.delete(id)}context.renderTimeline()};
  syncProps=()=>{const layer=selected();byId<HTMLElement>('noSelection').hidden=Boolean(layer);byId<HTMLElement>('properties').hidden=!layer;if(!layer)return;const content=byId<HTMLTextAreaElement>('propContent');content.value=layer.content||'';if(content.closest('label'))content.closest('label')!.hidden=layer.type!=='text';for(const [label,key] of [['Name','name'],['X','x'],['Y','y'],['Width','scaleX'],['Height','scaleY'],['Rotation','rotation'],['Opacity','opacity'],['Color','color']] as const){const input=byId<HTMLInputElement>(`prop${label}`),axis=key==='x'||key==='y',dimension=key==='x'?context.state.composition.width:key==='y'?context.state.composition.height:0,value=axis?Math.round(Number(layer[key])/100*dimension):layer[key];if(axis){input.min='0';input.max=String(dimension);input.step='1'}input.value=String(value);const output=document.getElementById(`out${label}`) as HTMLOutputElement|null;if(output)output.value=`${value}${axis?'px':key==='rotation'?'°':'%'}`}byId<HTMLButtonElement>('scaleLink').setAttribute('aria-pressed',String(layer.scaleLinked!==false))};
  selectLayer=id=>{selectOnly(context.state,id);document.querySelectorAll<HTMLElement>('.layer').forEach(element=>element.classList.toggle('selected',Number(element.dataset.id)===id));syncProps()};
  updateSelected=()=>{const layer=selected(),element=layer?.id===undefined?null:document.querySelector<HTMLElement>(`.layer[data-id="${layer.id}"]`);if(layer&&element)applyStyle(element,layer)};
  const addLayer=(type:string,content:string,name:string)=>{const layer=createLayer({id:context.nextId(),type,content,name,duration:context.state.duration});add(context.state,layer);renderLayers();if(layer.id!==undefined)selectLayer(layer.id);context.markDirty();return layer};
  for(const [label,key] of [['X','x'],['Y','y'],['Width','scaleX'],['Height','scaleY'],['Rotation','rotation'],['Opacity','opacity'],['Color','color']] as Array<[string,BasicKey]>){const input=byId<HTMLInputElement>(`prop${label}`);input.oninput=()=>{const layer=selected();if(!layer?.id)return;const dimension=key==='x'?context.state.composition.width:key==='y'?context.state.composition.height:0,value=key==='color'?input.value:dimension?Number(input.value)/dimension*100:Number(input.value),values:Record<string,unknown>={[key]:value};if(layer.scaleLinked&&(key==='scaleX'||key==='scaleY'))values[key==='scaleX'?'scaleY':'scaleX']=value;setAnimatedProperties(context.state,{id:layer.id,time:context.state.playback.time,values});updateSelected();syncProps();context.renderTimeline();context.markDirty()}}byId<HTMLButtonElement>('scaleLink').onclick=()=>{const layer=selected();if(!layer?.id)return;setProperties(context.state,{id:layer.id,values:{scaleLinked:layer.scaleLinked===false}});syncProps();context.markDirty()};for(const [id,key] of [['resetWidth','scaleX'],['resetHeight','scaleY']] as const)byId<HTMLButtonElement>(id).onclick=()=>{const layer=selected();if(!layer?.id)return;const values:Record<string,number>={[key]:100};if(layer.scaleLinked)values[key==='scaleX'?'scaleY':'scaleX']=100;setAnimatedProperties(context.state,{id:layer.id,time:context.state.playback.time,values});updateSelected();syncProps();context.renderTimeline();context.markDirty()};byId<HTMLInputElement>('propName').oninput=event=>{const layer=selected();if(!layer?.id)return;setProperties(context.state,{id:layer.id,values:{name:(event.currentTarget as HTMLInputElement).value}});context.renderTimeline();context.markDirty()};byId<HTMLTextAreaElement>('propContent').oninput=event=>{const layer=selected();if(!layer?.id)return;setProperties(context.state,{id:layer.id,values:{content:(event.currentTarget as HTMLTextAreaElement).value}});renderLayers();context.markDirty()};
  byId<HTMLElement>('stage').onclick=()=>selectLayer(null);byId<HTMLButtonElement>('addText').onclick=()=>addLayer('text',byId<HTMLInputElement>('textValue').value||'Texto','Texto');document.querySelectorAll<HTMLButtonElement>('[data-shape]').forEach(button=>button.onclick=()=>{const type=button.dataset.shape||'rect';addLayer(type,'',type==='circle'?'Círculo':'Retângulo')});
  return{addLayer,applyStyle,beginDrag,renderLayers,selectLayer,selected,syncProps,updateSelected};
}
