import type {History} from '../../core/history';
import {add} from '../../core/layer-commands';
import {createLayer,type Layer} from '../../core/project-model';
import {setProperties} from '../../core/project-commands';
import {selectOnly} from '../../core/selection-commands';
import type {EditorState} from '../../core/editor-state';
import type {MediaRuntime} from '../../renderer/media-runtime';

interface StageControllerContext {state:EditorState;mediaRuntime:MediaRuntime;nextId():number;history():History;snapshot():string;renderTimeline():void;markDirty():void;toast(message:string):void}
export interface StageController {addLayer(type:string,content:string,name:string):Layer;applyStyle(element:HTMLElement,layer:Layer):void;beginDrag(event:PointerEvent,layer:Layer):void;renderLayers():void;selectLayer(id:number|null):void;selected():Layer|null;syncProps():void;updateSelected():void}
type BasicKey='x'|'y'|'scale'|'rotation'|'opacity'|'color';
const byId=<T extends HTMLElement>(id:string):T=>{const element=document.getElementById(id);if(!element)throw new Error(`Elemento ausente: ${id}`);return element as T};

export function installStageController(context:StageControllerContext):StageController {
  let renderLayers=()=>{},syncProps=()=>{},selectLayer=(_id:number|null)=>{},updateSelected=()=>{};
  const selected=()=>context.state.layers.find(layer=>layer.id===context.state.selection.selected)||null;
  const applyStyle=(element:HTMLElement,layer:Layer)=>{element.style.left=`${layer.x}%`;element.style.top=`${layer.y}%`;element.style.opacity=String(layer.opacity/100);element.style.color=layer.color;element.style.backgroundColor=layer.type==='rect'||layer.type==='circle'?layer.color:'';element.style.filter=layer.filter;element.style.setProperty('--media-fit',layer.fitMode||'contain');element.style.transformOrigin=`${layer.anchorX??50}% ${layer.anchorY??50}%`;element.style.clipPath=`inset(${layer.cropY||0}% ${layer.cropX||0}%)`;element.style.transform=`translate(-50%,-50%) scale(${(layer.flipX?-1:1)*layer.scale/100},${(layer.flipY?-1:1)*layer.scale/100}) rotate(${layer.rotation}deg)`;element.style.visibility=layer.visible===false?'hidden':'visible';element.classList.toggle('selected',layer.id===context.state.selection.selected)};
  const beginDrag=(event:PointerEvent,layer:Layer)=>{if(layer.locked)return context.toast('Camada bloqueada');if(event.button!==0||layer.id===undefined)return;selectLayer(layer.id);const bounds=byId<HTMLElement>('stage').getBoundingClientRect(),before={x:layer.x,y:layer.y},history=context.history();history.begin(context.snapshot());const move=(pointer:PointerEvent)=>{setProperties(context.state,{id:layer.id!,values:{x:Math.max(0,Math.min(100,(pointer.clientX-bounds.left)/bounds.width*100)),y:Math.max(0,Math.min(100,(pointer.clientY-bounds.top)/bounds.height*100))}});updateSelected();syncProps();context.markDirty()};const up=(pointer:PointerEvent)=>{removeEventListener('pointermove',move);removeEventListener('pointerup',up);removeEventListener('pointercancel',up);if(pointer.type==='pointercancel'){setProperties(context.state,{id:layer.id!,values:before});history.cancel();updateSelected();syncProps()}else history.commit(context.snapshot());context.markDirty()};addEventListener('pointermove',move);addEventListener('pointerup',up);addEventListener('pointercancel',up)};
  renderLayers=()=>{const stage=byId<HTMLElement>('stage'),existing=new Map([...stage.querySelectorAll<HTMLElement>(':scope > .layer')].map(element=>[Number(element.dataset.id),element])),activeIds=new Set<number>();const hint=document.querySelector<HTMLElement>('.stage-hint');if(hint)hint.hidden=context.state.layers.length>0;for(const layer of context.state.layers){if(layer.id===undefined)continue;activeIds.add(layer.id);let element=existing.get(layer.id);if(element&&element.dataset.layerType!==layer.type){element.remove();element=undefined}if(!element){element=document.createElement('div');element.dataset.id=String(layer.id);element.dataset.layerType=layer.type}element.querySelectorAll('.transform-handle').forEach(handle=>handle.remove());element.className=`layer ${layer.type}${layer.type==='circle'?' shape circle':''}${layer.type==='image'||layer.type==='video'?' media-layer':''}`;if(['image','video','audio','drawing'].includes(layer.type)){context.mediaRuntime.attach(layer,element);if(layer.type==='audio')element.style.display='none'}else if(layer.type==='text')element.textContent=layer.content;else if(layer.type==='rect'||layer.type==='circle')element.classList.add('shape');applyStyle(element,layer);element.onpointerdown=event=>beginDrag(event,layer);element.onclick=event=>{event.stopPropagation();selectLayer(layer.id!)};if(element.parentElement!==stage)stage.append(element)}context.mediaRuntime.reconcile(context.state.layers);existing.forEach((element,id)=>{if(!activeIds.has(id))element.remove()});context.renderTimeline()};
  syncProps=()=>{const layer=selected();byId<HTMLElement>('noSelection').hidden=Boolean(layer);byId<HTMLElement>('properties').hidden=!layer;if(!layer)return;for(const [label,key] of [['Name','name'],['X','x'],['Y','y'],['Scale','scale'],['Rotation','rotation'],['Opacity','opacity'],['Color','color']] as const){byId<HTMLInputElement>(`prop${label}`).value=String(layer[key]);const output=document.getElementById(`out${label}`) as HTMLOutputElement|null;if(output)output.value=`${layer[key]}${key==='rotation'?'°':'%'}`}};
  selectLayer=id=>{selectOnly(context.state,id);document.querySelectorAll<HTMLElement>('.layer').forEach(element=>element.classList.toggle('selected',Number(element.dataset.id)===id));syncProps()};
  updateSelected=()=>{const layer=selected(),element=layer?.id===undefined?null:document.querySelector<HTMLElement>(`.layer[data-id="${layer.id}"]`);if(layer&&element)applyStyle(element,layer)};
  const addLayer=(type:string,content:string,name:string)=>{const layer=createLayer({id:context.nextId(),type,content,name,duration:context.state.duration});add(context.state,layer);renderLayers();if(layer.id!==undefined)selectLayer(layer.id);context.markDirty();return layer};
  for(const [label,key] of [['X','x'],['Y','y'],['Scale','scale'],['Rotation','rotation'],['Opacity','opacity'],['Color','color']] as Array<[string,BasicKey]>){const input=byId<HTMLInputElement>(`prop${label}`);input.oninput=()=>{const layer=selected();if(!layer?.id)return;setProperties(context.state,{id:layer.id,values:{[key]:key==='color'?input.value:Number(input.value)}});updateSelected();syncProps();context.markDirty()}}byId<HTMLInputElement>('propName').oninput=event=>{const layer=selected();if(!layer?.id)return;setProperties(context.state,{id:layer.id,values:{name:(event.currentTarget as HTMLInputElement).value}});context.renderTimeline();context.markDirty()};
  byId<HTMLElement>('stage').onclick=()=>selectLayer(null);byId<HTMLButtonElement>('addText').onclick=()=>addLayer('text',byId<HTMLInputElement>('textValue').value||'Texto','Texto');document.querySelectorAll<HTMLButtonElement>('[data-shape]').forEach(button=>button.onclick=()=>{const type=button.dataset.shape||'rect';addLayer(type,'',type==='circle'?'Círculo':'Retângulo')});
  return{addLayer,applyStyle,beginDrag,renderLayers,selectLayer,selected,syncProps,updateSelected};
}
