import {evaluateLayer} from '../core/animation';
import type {ProjectState} from '../core/editor-state';
import type {Layer} from '../core/project-model';

export type RenderableMedia=HTMLImageElement|HTMLVideoElement|HTMLCanvasElement;
export interface RasterMediaSource {get(layer:Layer):RenderableMedia|null}
export interface Rasterizer {draw(context:CanvasRenderingContext2D,canvas:HTMLCanvasElement,time:number,state:ProjectState,transparent?:boolean,layerSources?:Layer[]):void}

export function calculateMediaFit(sourceWidth:number,sourceHeight:number,frameWidth:number,frameHeight:number,mode='contain'):{width:number;height:number} {
  const sw=Math.max(1,sourceWidth),sh=Math.max(1,sourceHeight);if(mode==='fill')return{width:frameWidth,height:frameHeight};const scale=(mode==='cover'?Math.max:Math.min)(frameWidth/sw,frameHeight/sh);return{width:sw*scale,height:sh*scale};
}

export function create({document,media:mediaSource,viewport}:{document:Document;media:RasterMediaSource;viewport:()=>DOMRect}):Rasterizer {
  function canvasFill(ctx:CanvasRenderingContext2D,layer:Partial<Layer>,width:number,height:number):string|CanvasGradient {if(layer.fillType==='linear'){const angle=(layer.gradientAngle||0)*Math.PI/180,x=Math.cos(angle)*width/2,y=Math.sin(angle)*height/2,gradient=ctx.createLinearGradient(-x,-y,x,y);gradient.addColorStop(0,layer.color||'#fff');gradient.addColorStop(1,layer.gradientColor||'#7758ff');return gradient}if(layer.fillType==='radial'){const gradient=ctx.createRadialGradient(0,0,0,0,0,Math.max(width,height)/2);gradient.addColorStop(0,layer.color||'#fff');gradient.addColorStop(1,layer.gradientColor||'#7758ff');return gradient}return layer.color||'#fff'}
  function clipLayer(ctx:CanvasRenderingContext2D,layer:Partial<Layer>,width:number,height:number):void {const x=(50-(layer.anchorX??50))/100*width,y=(50-(layer.anchorY??50))/100*height;ctx.beginPath();if(layer.maskMode==='circle')ctx.arc(x,y,Math.min(width,height)*.48,0,Math.PI*2);else if(layer.maskMode==='ellipse')ctx.ellipse(x,y,width*.48,height*.42,0,0,Math.PI*2);else if(layer.maskMode==='polygon'&&layer.maskPoints&&layer.maskPoints.length>2){layer.maskPoints.forEach((point,index)=>{const px=x-width/2+point[0]/100*width,py=y-height/2+point[1]/100*height;index?ctx.lineTo(px,py):ctx.moveTo(px,py)});ctx.closePath()}else{const cropX=(layer.cropX||0)/100*width,cropY=(layer.cropY||0)/100*height;ctx.rect(x-width/2+cropX,y-height/2+cropY,width-cropX*2,height-cropY*2)}ctx.clip()}
  function mediaDimensions(media:RenderableMedia|VideoFrame):[number,number] {if(media instanceof VideoFrame)return[media.displayWidth,media.displayHeight];if(media instanceof HTMLVideoElement)return[media.videoWidth,media.videoHeight];if(media instanceof HTMLImageElement)return[media.naturalWidth,media.naturalHeight];return[media.width,media.height]}
  function chromaCanvas(media:RenderableMedia|VideoFrame,layer:Partial<Layer>):RenderableMedia|VideoFrame {const effects=layer.effects,tolerance=effects?.chromaTolerance||0,gains=[(effects?.redGain??100)/100,(effects?.greenGain??100)/100,(effects?.blueGain??100)/100],sharpen=(effects?.sharpen||0)/100,processing=tolerance||sharpen||gains.some(value=>value!==1);if(!processing)return media;const[sourceWidth,sourceHeight]=mediaDimensions(media);if(!sourceWidth||!sourceHeight)return media;const scale=Math.min(1,1280/sourceWidth),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(sourceWidth*scale));canvas.height=Math.max(1,Math.round(sourceHeight*scale));const context=canvas.getContext('2d',{willReadFrequently:true});if(!context)return media;context.drawImage(media,0,0,canvas.width,canvas.height);try{const image=context.getImageData(0,0,canvas.width,canvas.height),data=image.data,hex=typeof layer.chromaColor==='string'?layer.chromaColor:'#00ff00',target=[parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5,7),16)],limit=tolerance*4.42;for(let index=0;index<data.length;index+=4){if(tolerance){const distance=Math.hypot(data[index]-target[0],data[index+1]-target[1],data[index+2]-target[2]);if(distance<limit)data[index+3]=Math.round(255*distance/limit)}data[index]=Math.min(255,data[index]*gains[0]);data[index+1]=Math.min(255,data[index+1]*gains[1]);data[index+2]=Math.min(255,data[index+2]*gains[2])}if(sharpen){const original=new Uint8ClampedArray(data),width=canvas.width,height=canvas.height,amount=sharpen*.7;for(let y=1;y<height-1;y++)for(let x=1;x<width-1;x++){const index=(y*width+x)*4;for(let channel=0;channel<3;channel++)data[index+channel]=Math.max(0,Math.min(255,original[index+channel]*(1+4*amount)-amount*(original[index-4+channel]+original[index+4+channel]+original[index-width*4+channel]+original[index+width*4+channel])))}}context.putImageData(image,0,0)}catch{return media}return canvas}
  function vignette(ctx:CanvasRenderingContext2D,layer:Partial<Layer>,width:number,height:number,x:number,y:number):void {const amount=(layer.effects?.vignette||0)/100;if(!amount)return;const gradient=ctx.createRadialGradient(x,y,Math.min(width,height)*.2,x,y,Math.max(width,height)*.72);gradient.addColorStop(0,'rgba(0,0,0,0)');gradient.addColorStop(1,`rgba(0,0,0,${amount})`);ctx.fillStyle=gradient;ctx.fillRect(x-width/2,y-height/2,width,height)}
  function draw(ctx:CanvasRenderingContext2D,canvas:HTMLCanvasElement,time:number,state:ProjectState,transparent=false,layerSources=state.layers):void {
    ctx.clearRect(0,0,canvas.width,canvas.height);if(!transparent){ctx.save();ctx.fillStyle=state.composition.background||'#08090b';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.restore()}
    const stageRect=viewport(),scaleX=canvas.width/stageRect.width,scaleY=canvas.height/stageRect.height;
    for(const source of layerSources){if(source.visible===false||source.type==='audio'||time<source.start||time>=source.end)continue;const layer=evaluateLayer(source,time,{layers:state.layers,duration:state.duration});ctx.save();ctx.globalAlpha=(layer.opacity??100)/100;ctx.globalCompositeOperation=(layer.blend==='normal'?'source-over':layer.blend||'source-over') as GlobalCompositeOperation;ctx.filter=typeof layer.filter==='string'?(layer.filter||'none').replace(/url\([^)]*\)\s*/g,'')||'none':'none';ctx.translate((layer.x??50)/100*canvas.width,(layer.y??50)/100*canvas.height);ctx.rotate((layer.rotation||0)*Math.PI/180);ctx.scale((layer.flipX?-1:1)*(layer.scale||100)/100,(layer.flipY?-1:1)*(layer.scale||100)/100);ctx.fillStyle=layer.color||'#fff';ctx.strokeStyle=layer.strokeColor||'#000';ctx.lineWidth=(layer.stroke||0)*Math.max(scaleX,scaleY);
      if(layer.type==='text'){ctx.font=`700 ${(layer.fontSize||42)*scaleY}px ${layer.font||'Segoe UI'}`;ctx.textAlign='center';ctx.textBaseline='middle';if(layer.stroke)ctx.strokeText(layer.content||'',0,0);ctx.fillText(layer.content||'',0,0)}
      else if(layer.type==='rect'){const width=160*scaleX,height=100*scaleY,radius=Math.min(layer.radius||0,50)/100*Math.min(width,height);ctx.fillStyle=canvasFill(ctx,layer,width,height);clipLayer(ctx,layer,width,height);ctx.beginPath();ctx.roundRect(-width/2,-height/2,width,height,radius);ctx.fill();if(layer.stroke)ctx.stroke()}
      else if(layer.type==='circle'){const size=120*Math.min(scaleX,scaleY);ctx.fillStyle=canvasFill(ctx,layer,size,size);ctx.beginPath();ctx.arc(0,0,size/2,0,Math.PI*2);ctx.fill();if(layer.stroke)ctx.stroke()}
      else if(layer.type==='path'&&layer.pathPoints?.length){ctx.beginPath();const points=layer.pathPoints.map(point=>[(point[0]-50)*canvas.width,(point[1]-50)*canvas.height] as [number,number]);ctx.moveTo(...points[0]);for(let index=1;index<points.length-1;index++){const middle:[number,number]=[(points[index][0]+points[index+1][0])/2,(points[index][1]+points[index+1][1])/2];ctx.quadraticCurveTo(points[index][0],points[index][1],...middle)}if(points.length>1)ctx.lineTo(...points[points.length-1]);ctx.strokeStyle=layer.color||'#fff';ctx.lineWidth=Math.max(1,(layer.stroke||2)*Math.max(scaleX,scaleY));ctx.lineCap='round';ctx.lineJoin='round';ctx.stroke()}
      else if(layer.type!=='null'){const media=mediaSource.get(source);if(media){const[sourceWidth,sourceHeight]=mediaDimensions(media),fit=calculateMediaFit(sourceWidth||source.mediaWidth||1,sourceHeight||source.mediaHeight||1,canvas.width,canvas.height,source.fitMode||'contain'),width=fit.width,height=fit.height,x=(50-(layer.anchorX??50))/100*width,y=(50-(layer.anchorY??50))/100*height;let frame:VideoFrame|undefined;try{if(media instanceof HTMLVideoElement)frame=new VideoFrame(media);clipLayer(ctx,layer,width,height);ctx.drawImage(chromaCanvas(frame||media,layer),x-width/2,y-height/2,width,height);vignette(ctx,layer,width,height,x,y)}catch{}finally{frame?.close()}}}ctx.restore();
    }
  }
  return{draw};
}
