import {addToLibrary,configureLayer,replaceLibrary} from '../../core/media-commands';
import {setLayerWaveform,setProperties} from '../../core/project-commands';
import type {EditorState,MediaLibraryEntry,ProjectState} from '../../core/editor-state';
import type {Layer} from '../../core/project-model';
import type {MediaRuntime,ProxyMetadata} from '../../renderer/media-runtime';
import {waveformFromFile} from './audio-waveform';

interface MediaBridge {getPathForFile?(file:File):string;probeMedia?(path:string):Promise<Partial<MediaLibraryEntry>>;fileUrl?(path:string):string}
interface AddMediaOptions {addToLibrary?:boolean;createLayer?:boolean}
interface DropPoint {x:number;y:number}
interface MediaLibraryContext {
  state:EditorState;mediaRuntime:MediaRuntime;bridge?:MediaBridge;addLayer(type:string,content:string,name:string):Layer;syncComposition():void;renderLayers():void;selectLayer(id:number):void;switchPanel(name:string):void;toast(message:string):void;
}
export interface MediaLibraryController {addMediaDescriptor(descriptor:MediaLibraryEntry,options?:AddMediaOptions):Layer|null;renderMediaLibrary():void;restoreMediaLibrary(data:ProjectState):void;importMedia(file:File):Promise<Layer|null>}

const byId=<T extends HTMLElement>(id:string):T=>{const element=document.getElementById(id);if(!element)throw new Error(`Elemento ausente: ${id}`);return element as T};
const clamp=(value:number)=>Math.max(0,Math.min(100,value));
const supportedMedia=(file:File)=>/^(video|image|audio)\//i.test(file.type||'')||/\.(mp4|mov|mkv|webm|avi|m4v|jpg|jpeg|png|gif|webp|bmp|mp3|wav|m4a|aac|ogg|flac)$/i.test(file.name||'');
const mediaType=(file:File):'video'|'image'|'audio'=>file.type.startsWith('video')||/\.(mp4|mov|mkv|webm|avi|m4v)$/i.test(file.name)?'video':file.type.startsWith('audio')||/\.(mp3|wav|m4a|aac|ogg|flac)$/i.test(file.name)?'audio':'image';
const browserMetadata=(type:string,url:string):Promise<Partial<MediaLibraryEntry>>=>new Promise(resolve=>{const media=type==='image'?document.createElement('img'):document.createElement(type==='video'?'video':'audio'),finish=()=>resolve({duration:media instanceof HTMLMediaElement&&Number.isFinite(media.duration)?media.duration:0,width:media instanceof HTMLVideoElement?media.videoWidth:media instanceof HTMLImageElement?media.naturalWidth||0:0,height:media instanceof HTMLVideoElement?media.videoHeight:media instanceof HTMLImageElement?media.naturalHeight||0:0,rotation:0,hasAudio:type!=='image'});if(media instanceof HTMLMediaElement){media.preload='metadata';media.onloadedmetadata=finish}else media.onload=finish;media.onerror=finish;media.src=url});

export function installMediaLibraryController(context:MediaLibraryContext):MediaLibraryController {
  const requestProxy=(layer:Layer,metadata:ProxyMetadata)=>context.mediaRuntime.proxy(layer,metadata).catch(error=>console.warn('Proxy indisponível; usando original.',error));
  let addMediaDescriptor:(descriptor:MediaLibraryEntry,options?:AddMediaOptions)=>Layer|null;
  const renderMediaLibrary=()=>{const list=byId<HTMLElement>('mediaList');list.replaceChildren();for(const descriptor of context.state.mediaLibrary||[]){const item=document.createElement('div');item.className='asset';item.textContent=descriptor.name;item.title=descriptor.sourcePath||descriptor.name;item.onclick=()=>addMediaDescriptor(descriptor,{addToLibrary:false});list.append(item)}if(!list.children.length){const empty=document.createElement('div');empty.className='empty';empty.textContent='Seus arquivos aparecerão aqui';list.append(empty)}};
  addMediaDescriptor=(descriptor,options={})=>{const {type,url,name}=descriptor;const create=()=>{const previousDuration=context.state.duration,layer=context.addLayer(type,url,name);if(layer.id===undefined)throw new Error('Camada de mídia criada sem ID');configureLayer(context.state,{id:layer.id,source:descriptor});if(context.state.duration!==previousDuration)context.syncComposition();context.renderLayers();context.selectLayer(layer.id);if(type==='video')void requestProxy(layer,{width:descriptor.width,height:descriptor.height,duration:descriptor.duration});return layer};if(options.addToLibrary!==false){addToLibrary(context.state,descriptor);renderMediaLibrary()}return options.createLayer===false?null:create()};
  const restoreMediaLibrary=(data:ProjectState)=>{const entries=[...(data.mediaLibrary||[]),...data.layers.filter(layer=>['image','video','audio'].includes(layer.type)).map(layer=>({type:layer.type,url:layer.content,sourcePath:layer.sourcePath,name:layer.name,duration:layer.mediaDuration,width:layer.mediaWidth,height:layer.mediaHeight,rotation:layer.mediaRotation,fps:layer.mediaFps}))];replaceLibrary(context.state,entries.map(entry=>({...entry,url:entry.sourcePath&&context.bridge?.fileUrl?context.bridge.fileUrl(entry.sourcePath):entry.url})).filter(entry=>entry.url));renderMediaLibrary()};
  const importMedia=async(file:File):Promise<Layer|null>=>{const url=URL.createObjectURL(file),type=mediaType(file),sourcePath=context.bridge?.getPathForFile?.(file)||'';let metadata:Partial<MediaLibraryEntry>|undefined;if(sourcePath&&context.bridge?.probeMedia)try{metadata=await context.bridge.probeMedia(sourcePath)}catch(error){console.warn('FFprobe não conseguiu ler a mídia; usando metadados do navegador.',error)}if(type==='audio'?!metadata?.duration:!metadata?.width||!metadata?.height)metadata={...(metadata||{}),...await browserMetadata(type,url)};const waveform=type==='audio'||type==='video'&&metadata?.hasAudio?await waveformFromFile(file):[];const layer=addMediaDescriptor({type,url,name:file.name,sourcePath,duration:metadata?.duration||0,width:metadata?.width||0,height:metadata?.height||0,rotation:metadata?.rotation||0,hasAudio:type==='audio'||!!metadata?.hasAudio,waveform});if(layer?.id!==undefined&&waveform.length)setLayerWaveform(context.state,{id:layer.id,points:waveform,hasAudio:true});return layer};
  const importFiles=async(files:FileList|File[],dropPoint:DropPoint|null=null)=>{const accepted=[...files].filter(supportedMedia);let added=0;for(const file of accepted){const layer=await importMedia(file);if(layer){if(dropPoint&&layer.type!=='audio'&&layer.id!==undefined){setProperties(context.state,{id:layer.id,values:{x:clamp(dropPoint.x+added*2),y:clamp(dropPoint.y+added*2)}});context.renderLayers();context.selectLayer(layer.id)}added++}}if(added){context.switchPanel('media');context.toast(`${added} ${added===1?'arquivo adicionado':'arquivos adicionados'} como ${added===1?'camada':'camadas'}`)}else context.toast('Solte arquivos de vídeo, imagem ou áudio compatíveis');return added};
  byId<HTMLInputElement>('mediaInput').onchange=async event=>{const input=event.currentTarget as HTMLInputElement;if(input.files)await importFiles(input.files);input.value=''};
  const transferHasFiles=(event:DragEvent)=>[...(event.dataTransfer?.types||[])].includes('Files');document.addEventListener('dragenter',event=>{if(!transferHasFiles(event))return;event.preventDefault();document.body.classList.add('media-dragging')});document.addEventListener('dragover',event=>{if(!transferHasFiles(event))return;event.preventDefault();if(event.dataTransfer)event.dataTransfer.dropEffect='copy';document.body.classList.add('media-dragging')});document.addEventListener('dragleave',event=>{if(!event.relatedTarget)document.body.classList.remove('media-dragging')});document.addEventListener('drop',async event=>{if(!event.dataTransfer?.files.length)return;event.preventDefault();document.body.classList.remove('media-dragging');const rect=byId<HTMLElement>('stage').getBoundingClientRect(),inside=event.clientX>=rect.left&&event.clientX<=rect.right&&event.clientY>=rect.top&&event.clientY<=rect.bottom,point=inside?{x:(event.clientX-rect.left)/rect.width*100,y:(event.clientY-rect.top)/rect.height*100}:null;await importFiles(event.dataTransfer.files,point)});
  return{addMediaDescriptor,renderMediaLibrary,restoreMediaLibrary,importMedia};
}
